import fs from 'node:fs';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import {chromium} from '/workspace/oda-reference-redesign/node_modules/playwright/index.mjs';
import AxeBuilder from '/workspace/oda-reference-redesign/node_modules/@axe-core/playwright/dist/index.mjs';
import {makeSeed} from './fixture.mjs';

if(process.env.ODA_FINAL_QA_GO!=='1')throw Error('Root final build GO required');
const repo='/workspace/oda-reference-redesign',root='/workspace/scratch/oda-reference-redesign/domino-palette/browser-qa';
const receiptPath=process.env.ODA_BUILD_RECEIPT;
if(!receiptPath)throw Error('Explicit receipt required');
const receipt=JSON.parse(fs.readFileSync(receiptPath));
const out=root+'/'+(process.env.ODA_QA_MODE||'final')+'/functional';fs.mkdirSync(out,{recursive:true});
const sha=b=>createHash('sha256').update(b).digest('hex');
function verify(){const all=[...receipt.source,...receipt.build];for(const a of all){const b=fs.readFileSync(repo+'/'+a.file);assert.equal(b.length,a.bytes,a.file+' bytes');assert.equal(sha(b),a.sha256,a.file+' SHA256')}return{source:receipt.source.length,build:receipt.build.length}}
const report={sourceCommit:receipt.sourceCommit,checkoutHead:execFileSync('git',['rev-parse','HEAD'],{cwd:repo,encoding:'utf8'}).trim(),synthetic:true,physicalDevice:false,receiptPath,hashesBefore:verify(),startedAtUtc:new Date().toISOString(),checks:[],screenshots:[],contrast:[],servedResponses:[],externalBlocked:[],pageErrors:[],notes:['Desktop/narrow Chromium viewport emulation; not a physical phone.','TwoMinuteStart exposes Stop rather than Pause; pause/resume checked in existing completion timer.','Synthetic isolated native-browser records only; production records never read or written.']};
const base='http://127.0.0.1:4194/one-decision-away/',now='2026-10-03T12:00:00.000Z';
const pending=[];
const pass=(name,data={})=>report.checks.push({name,pass:true,...data});
const contrast=(a,b)=>{const lum=c=>{let v=c.match(/[\d.]+/g).slice(0,3).map(x=>Number(x)/255).map(x=>x<=.04045?x/12.92:((x+.055)/1.055)**2.4);return v[0]*.2126+v[1]*.7152+v[2]*.0722};return(Math.max(lum(a),lum(b))+.05)/(Math.min(lum(a),lum(b))+.05)};
const browser=await chromium.launch({executablePath:'/usr/bin/chromium'});
async function open(width,kind='active'){
 const context=await browser.newContext({viewport:{width,height:width===1440?1000:844},timezoneId:'UTC',locale:'en-US',reducedMotion:'reduce',serviceWorkers:'block'});
 await context.route('**/*',r=>{let u=new URL(r.request().url());if(u.origin===new URL(base).origin)return r.continue();report.externalBlocked.push(u.origin+u.pathname);return r.abort()});
 await context.addInitScript(d=>{localStorage.setItem('one_decision_away_app_data_v1',JSON.stringify(d));localStorage.setItem('oda_locale','en');localStorage.setItem('oda_theme','light')},makeSeed(kind));
 const page=await context.newPage();await page.clock.install({time:new Date(now)});page.on('pageerror',e=>report.pageErrors.push(e.message));page.on('response',r=>{let u=new URL(r.url());if(u.origin!==new URL(base).origin)return;let rel=u.pathname.slice('/one-decision-away/'.length);if(!rel)rel='index.html';const expected=receipt.build.find(x=>x.file==='dist/'+rel);if(expected&&(/\.(js|css)$/.test(rel)||rel==='index.html'))pending.push((async()=>{const b=await r.body();assert.equal(sha(b),expected.sha256,'Actual HTTP body '+rel);report.servedResponses.push({file:expected.file,status:r.status(),bytes:b.length,sha256:sha(b)})})())});
 await page.goto(base+'#/app');await page.locator('.oda-decision-text').waitFor();await page.evaluate(()=>document.fonts.ready);await page.waitForTimeout(150);return{page,context};
}
async function screenshot(page,name,fullPage=false){const file=name+'.png';await page.screenshot({path:out+'/'+file,animations:'disabled',fullPage});const b=fs.readFileSync(out+'/'+file);report.screenshots.push({file,bytes:b.length,sha256:sha(b)})}
async function styles(locator){return locator.evaluate(e=>{const c=getComputedStyle(e),r=e.getBoundingClientRect();return{color:c.color,bg:c.backgroundColor,image:c.backgroundImage,outline:c.outlineColor,outlineWidth:c.outlineWidth,outlineOffset:c.outlineOffset,shadow:c.boxShadow,border:c.borderColor,opacity:c.opacity,rect:{x:r.x,y:r.y,width:r.width,height:r.height}}})}
async function axe(page,name){const r=await new AxeBuilder({page}).withRules(['color-contrast']).analyze();const entry={name,passes:r.passes.map(x=>({id:x.id,nodes:x.nodes.length})),violations:r.violations.map(v=>({id:v.id,impact:v.impact,nodes:v.nodes.map(n=>({target:n.target,html:n.html,summary:n.failureSummary,any:n.any.map(a=>({message:a.message,data:a.data}))}))})),incomplete:r.incomplete.map(v=>({id:v.id,nodes:v.nodes.map(n=>({target:n.target,summary:n.failureSummary}))}))};report.contrast.push(entry);if(entry.violations.length)report.checks.push({name:name+' automated contrast',pass:false,violations:entry.violations});else pass(name+' automated contrast',{incomplete:entry.incomplete.length})}
async function noOverflow(page,name){const v=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth,body:document.body.scrollWidth}));assert.equal(v.scroll,v.width);assert.equal(v.body,v.width);pass(name+' no horizontal overflow',v)}
const read=page=>page.evaluate(()=>JSON.parse(localStorage.getItem('one_decision_away_app_data_v1')));
async function waitRecord(page,predicate){for(let i=0;i<60;i++){const d=await read(page);if(predicate(d))return d;await page.waitForTimeout(50)}throw Error('Record write did not settle')}
try{
 for(const width of [1440,390,320]){const c=await open(width);try{
  await noOverflow(c.page,'Active Today '+width);const p=c.page;
  const button=p.locator('.oda-decision-action'),normal=await styles(button);assert.ok(contrast(normal.color,normal.bg)>=4.5);pass('CTA normal contrast '+width,{ratio:contrast(normal.color,normal.bg),normal});
  await button.hover();await p.waitForTimeout(200);const hover=await styles(button);assert.ok(contrast(hover.color,hover.bg)>=4.5);pass('CTA hover contrast '+width,{ratio:contrast(hover.color,hover.bg),hover});
  await p.keyboard.press('Tab');await button.focus();const focus=await styles(button);assert.notEqual(focus.outlineWidth,'0px');pass('Dark CTA focus '+width,focus);await screenshot(p,'dark-focus-'+width);await button.blur();
  const touch=await p.locator('.oda-decision-action,.oda-decision-done,.oda-hybrid-action,.oda-tab').evaluateAll(es=>es.map(e=>{let r=e.getBoundingClientRect();return{text:e.textContent.trim(),w:r.width,h:r.height,display:getComputedStyle(e).display}}).filter(x=>x.display!=='none'&&x.w&&x.h));assert.ok(touch.every(x=>x.w>=44&&x.h>=44));pass('Primary action/navigation touch targets '+width,{touch});
  const ring=await p.locator('.oda-hybrid-ring').evaluate(e=>({value:e.getAttribute('aria-valuenow'),max:e.getAttribute('aria-valuemax'),image:getComputedStyle(e).backgroundImage,text:e.textContent}));assert.equal(ring.value,'1');assert.equal(ring.max,'103');assert.match(ring.text,/1%/);pass('Real lesson progress '+width,{ring});
  assert.equal(await p.locator('.oda-decision-text').innerText(),'Read two pages');assert.match(await p.locator('.oda-decision-plan').innerText(),/Then I will put it aside and read one paragraph\./);pass('Natural decision/plan text '+width);
  await axe(p,'Active Today '+width);
  if(width!==1440){await p.locator('.oda-hybrid-actions').scrollIntoViewIfNeeded();await screenshot(p,'actions-'+width);}
 }finally{await c.context.close()}}
 const empty=await open(320,'empty');try{const p=empty.page;const b=p.locator('.oda-decision-action');assert.equal(await b.isDisabled(),true);const disabled=await styles(b);assert.notEqual(disabled.bg,'rgb(197, 22, 36)');pass('Empty decision button disabled state',{disabled});await screenshot(p,'empty-disabled-320');await p.locator('#today-decision-input').fill('Take a short walk');assert.equal(await b.isDisabled(),false);await p.keyboard.press('Tab');await b.focus();pass('Empty form keyboard focus',await styles(b));await b.click();await p.locator('.oda-decision-text').filter({hasText:'Take a short walk'}).waitFor();pass('Empty form saves ordinary decision');await noOverflow(p,'New decision320');await axe(p,'New decision320')}finally{await empty.context.close()}
 const c=await open(390);try{const p=c.page;
  // Palette must leave Today when navigating through real app controls.
  await p.getByRole('button',{name:'Notebook',exact:true}).last().click();await p.locator('#notebook-journal-content').waitFor();assert.equal(await p.locator('[data-app-route]').getAttribute('data-app-route'),'/app/notebook');const nonToday=await styles(p.locator('.oda-reference-app'));assert.notEqual(nonToday.bg,'rgb(247, 242, 234)');await p.getByRole('button',{name:'Today',exact:true}).last().click();await p.locator('.oda-decision-text').waitFor();const today=await styles(p.locator('.oda-reference-app'));assert.equal(today.bg,'rgb(247, 242, 234)');pass('Route switch restores non-Today palette',{nonToday,today});
  // Habits remain non-color checked states with one native write.
  const habit=p.locator('.oda-hybrid-action').filter({hasText:'Drink a glass of water'});await habit.click();await p.waitForFunction(()=>[...document.querySelectorAll('.oda-hybrid-action')].find(e=>e.textContent.includes('Drink a glass of water'))?.getAttribute('aria-pressed')==='true');assert.equal(await habit.getAttribute('aria-pressed'),'true');assert.equal(await habit.locator('svg').count(),1);await habit.click();await p.waitForFunction(()=>[...document.querySelectorAll('.oda-hybrid-action')].find(e=>e.textContent.includes('Drink a glass of water'))?.getAttribute('aria-pressed')==='false');assert.equal(await habit.getAttribute('aria-pressed'),'false');pass('Habit toggle state/icon persists');
  await p.locator('.oda-decision-plan').click();await p.locator('#plan-then').fill('put my phone away and read one paragraph.');await p.getByRole('button',{name:'Unclear',exact:true}).click().catch(()=>{});await p.keyboard.press('Tab');await p.locator('#plan-then').focus();const lightFocus=await styles(p.locator('#plan-then'));assert.notEqual(lightFocus.outlineWidth,'0px');pass('Light planning field focus',lightFocus);await screenshot(p,'plan-focus-390');await axe(p,'Planning sheet390');
  await p.evaluate(()=>{const original=IDBObjectStore.prototype.put;window.__paletteFault={armed:true,thrown:0};IDBObjectStore.prototype.put=function(value,key){if(this.name==='record'&&key==='current'&&window.__paletteFault.armed){window.__paletteFault.armed=false;window.__paletteFault.thrown++;throw new DOMException('Synthetic palette QA native save failure','QuotaExceededError')}return original.call(this,value,key)}});
  await p.getByRole('button',{name:'Save plan',exact:true}).click();const alert=p.getByRole('alert').filter({hasText:'Could not save this change'});await alert.waitFor();assert.equal(await p.locator('#plan-then').inputValue(),'put my phone away and read one paragraph.');const semantic=await styles(alert);assert.notEqual(semantic.color,lightFocus.color);pass('Native plan failure keeps draft and semantic error',{semantic});await screenshot(p,'plan-error-390');await axe(p,'Plan error390');await p.getByRole('button',{name:'Save plan',exact:true}).click();await p.locator('#plan-then').waitFor({state:'detached'});const d=await waitRecord(p,d=>d.missions.find(m=>m.id==='synthetic-palette-decision').plan.ifThen==='put my phone away and read one paragraph.');pass('Plan retry commits ordinary copy once',{fault:await p.evaluate(()=>window.__paletteFault),completions:d.completions.length});await screenshot(p,'plan-success-390');
  await p.locator('.oda-decision-action').click();const timer=p.getByRole('timer');await timer.waitFor();assert.match(await timer.getAttribute('aria-label'),/2:00/);await p.clock.fastForward(10000);assert.match(await timer.getAttribute('aria-label'),/1:50/);await p.getByRole('button',{name:'Stop',exact:true}).click();assert.equal(await timer.count(),0);pass('Two-minute wall-clock start/Stop');await p.locator('.oda-decision-action').click();await timer.waitFor();assert.match(await timer.getAttribute('aria-label'),/2:00/);await p.clock.fastForward(120100);await p.getByRole('button',{name:'I did it — mark as done',exact:true}).waitFor();pass('Two-minute completion precisely reaches120seconds');await screenshot(p,'two-minute-complete-390');await p.getByRole('button',{name:'I did it — mark as done',exact:true}).click();await p.locator('#q1').waitFor();const confirm=p.getByRole('button',{name:'Confirm',exact:true});await p.locator('#q1').fill('');assert.equal(await confirm.isDisabled(),true);pass('Completion disabled when reflection cleared');
  await p.getByRole('button',{name:'Timer',exact:true}).click();await p.getByRole('button',{name:'Start',exact:true}).click();await p.clock.fastForward(10000);await p.getByRole('button',{name:'Pause',exact:true}).click();const dialog=p.getByRole('dialog'),paused=await dialog.innerText();await p.clock.fastForward(5000);assert.equal(await dialog.innerText(),paused);await p.getByRole('button',{name:'Start',exact:true}).click();await p.clock.fastForward(1000);assert.notEqual(await dialog.innerText(),paused);await p.getByRole('button',{name:'Reset',exact:true}).click();pass('Completion timer pause/resume/reset');await p.getByRole('button',{name:'Done',exact:true}).click();await p.locator('#q1').fill('I read two pages.');await screenshot(p,'completion-ready-390');await axe(p,'Completion sheet390');const before=await read(p);await confirm.evaluate(e=>{e.click();e.click();e.click()});await p.locator('.oda-decision-kept').waitFor();const after=await waitRecord(p,d=>d.completions.length===1);assert.equal(after.completions.length,1);assert.equal(after.transactions.filter(t=>t.kind==='one_decision_reward').length,1);assert.equal(after.transactions.filter(t=>t.kind==='one_decision_reward')[0].amount,500);pass('Repeat confirmation grants one500reward/keptdecision',{completions:after.completions.length,rewardTransactions:after.transactions.filter(t=>t.kind==='one_decision_reward'),beforeTransactions:before.transactions.length,afterTransactions:after.transactions.length});await screenshot(p,'completed-decision-390');await noOverflow(p,'Completed Today390');await axe(p,'Completed Today390');assert.equal(await p.locator('.oda-hybrid-action').first().isDisabled(),true);pass('Completed action distinguished by disabled and checked state');
 }finally{await c.context.close()}
 await Promise.all(pending);assert.deepEqual(report.externalBlocked,[]);assert.deepEqual(report.pageErrors,[]);pass('No external attempts or browser page errors');report.hashesAfter=verify();report.finishedAtUtc=new Date().toISOString();
}catch(e){report.error={name:e.name,message:e.message,stack:e.stack};throw e}finally{await browser.close();fs.writeFileSync(out+'/report.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({sourceCommit:report.sourceCommit,checks:report.checks.length,failed:report.checks.filter(x=>!x.pass).length,screenshots:report.screenshots.length,error:report.error}))}
