import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import {chromium} from '/workspace/oda-landing-photographic/node_modules/playwright/index.mjs';
import {makeSeed} from './fixture.mjs';
import {actualTextContrast} from './contrast-capture.mjs';
import {actualFocusContrast} from './focus-capture.mjs';

if(process.env.ODA_LANDING_STATES_GO!=='1')throw Error('Scoped frozen-build GO is required');
const repo='/workspace/oda-landing-photographic',root='/workspace/scratch/oda-landing-photographic/browser-qa';
const receiptPath='/workspace/scratch/oda-landing-photographic/corrected-build/build-receipt.json';
const expectedCommit='9627fa22c379f15755d9388d7fbaf49c27c6457c',expectedReceiptSha='2b6537d8a50cfbf75ba27781a061ee9d68d161c90734e42f8cc80ec8e3550f6f';
const base='http://127.0.0.1:4197/one-decision-away/',origin=new URL(base),sha=b=>createHash('sha256').update(b).digest('hex');
const receiptBytes=fs.readFileSync(receiptPath),receipt=JSON.parse(receiptBytes);assert.equal(sha(receiptBytes),expectedReceiptSha);assert.equal(receipt.sourceCommit,expectedCommit);
const primarySelector='.oda-landing-hero-actions .oda-landing-button-primary',navSelector='.oda-landing-nav-actions > .oda-landing-button-plain';
const statesRoot=root+'/states';fs.mkdirSync(statesRoot,{recursive:true});const next=Math.max(0,...fs.readdirSync(statesRoot).map(name=>Number(name.match(/^attempt-(\d+)$/)?.[1]??0)))+1;
const out=statesRoot+'/attempt-'+next;fs.mkdirSync(out);
const fingerprint=file=>{const b=fs.readFileSync(file);return{file,bytes:b.length,sha256:sha(b)}};
const reusePath=statesRoot+'/attempt-2/report.json',reuse=JSON.parse(fs.readFileSync(reusePath));assert.equal(reuse.sourceCommit,expectedCommit);assert.equal(reuse.receiptSha256,expectedReceiptSha);assert.deepEqual(reuse.hashesBefore,reuse.hashesAfter);const reuse1440=reuse.cases.find(row=>row.width===1440);assert.equal(reuse1440.states.length,3);assert.ok(reuse1440.states.every(item=>item.analysis.pass));assert.equal(reuse1440.focus.find(item=>item.label==='primary').analysis.pass,true);for(const png of reuse.pngs){const actual=fingerprint(path.join(path.dirname(reusePath),png.file));assert.equal(actual.bytes,png.bytes);assert.equal(actual.sha256,png.sha256)}
function verify(){assert.equal(execFileSync('git',['rev-parse','HEAD'],{cwd:repo,encoding:'utf8'}).trim(),expectedCommit);assert.equal(sha(fs.readFileSync(receiptPath)),expectedReceiptSha);let bytes=0;for(const entry of [...receipt.source,...receipt.build]){const b=fs.readFileSync(path.join(repo,entry.file));assert.equal(b.length,entry.bytes,entry.file);assert.equal(sha(b),entry.sha256,entry.file);bytes+=b.length}return{sourceFiles:receipt.source.length,buildFiles:receipt.build.length,totalBytes:bytes,sourceCommit:expectedCommit,receiptSha256:expectedReceiptSha}}
const report={scope:'Supplemental EN/light primary CTA default/hover/active text and keyboard primary/nav focus-outline samples at 1440/390/320; exact frozen localhost build.',sourceCommit:expectedCommit,receiptPath,receiptSha256:expectedReceiptSha,base,synthetic:true,physicalDevice:false,published:false,startedAtUtc:new Date().toISOString(),attempt:next,cases:[],checks:[],pngs:[],servedResponses:[],externalBlocked:[],pageErrors:[],responseErrors:[],pass:false,limits:['Paired actual browser PNGs with computed styles; no image regeneration.','Focus outline samples are essential nontext UI mark measurements at 3:1; text uses its applicable threshold.','This is scoped synthetic-browser evidence, not broad QA, focus-area compliance, human listening, native-device testing, or publication.']};
report.reusedEvidence={reason:'Parent authorized retaining already-passed desktop CTA states and primary focus after harmless absent/empty inline-style bookkeeping failure. Resume nav1440 plus mobile states/focus only.',report:fingerprint(reusePath),seal:fingerprint(path.dirname(reusePath)+'/seal.json'),helpers:reuse.helpersBefore,rawLog:fingerprint(statesRoot+'/runtime-2.log')};
const check=(name,detail={})=>{report.checks.push({name,pass:true,...detail});console.log(JSON.stringify({check:name,...detail}))};
let browser;
const pending=[];
async function open(width){
 const context=await browser.newContext({viewport:{width,height:width===1440?1000:844},locale:'en-US',timezoneId:'UTC',colorScheme:'light',reducedMotion:'reduce',serviceWorkers:'block'});
 await context.route('**/*',route=>{const u=new URL(route.request().url());if(u.origin===origin.origin&&u.pathname.startsWith(origin.pathname)&&route.request().method()==='GET')return route.continue();report.externalBlocked.push({method:route.request().method(),url:u.origin+u.pathname});return route.abort()});
 const seed=makeSeed();await context.addInitScript(seed=>{localStorage.setItem('one_decision_away_app_data_v1',JSON.stringify(seed));localStorage.setItem('oda_locale','en');localStorage.setItem('oda_theme','light')},seed);
 const page=await context.newPage();await page.clock.setFixedTime(new Date('2026-10-03T12:00:00.000Z'));page.on('pageerror',error=>report.pageErrors.push({width,message:error.message}));
 const rows=[],requests=[];context.on('request',request=>requests.push({url:request.url(),method:request.method()}));
 page.on('response',response=>{const u=new URL(response.url());if(u.origin!==origin.origin)return;const rel=u.pathname.slice(origin.pathname.length)||'index.html',entry=receipt.build.find(item=>item.file==='dist/'+rel);if(!entry)return;pending.push((async()=>{const b=await response.body(),row={width,file:entry.file,status:response.status(),bytes:b.length,sha256:sha(b)};assert.equal(row.status,200);assert.equal(row.bytes,entry.bytes,'Served '+entry.file);assert.equal(row.sha256,entry.sha256,'Served '+entry.file);rows.push(row);report.servedResponses.push(row)})().catch(error=>report.responseErrors.push({width,message:error.message})))});
 return{context,page,rows,requests};
}
const style=locator=>locator.evaluate(element=>{const c=getComputedStyle(element),r=element.getBoundingClientRect();return{color:c.color,backgroundColor:c.backgroundColor,backgroundImage:c.backgroundImage,boxShadow:c.boxShadow,outlineColor:c.outlineColor,outlineStyle:c.outlineStyle,outlineWidth:c.outlineWidth,outlineOffset:c.outlineOffset,fontSize:c.fontSize,fontWeight:c.fontWeight,hover:element.matches(':hover'),active:element.matches(':active'),focusVisible:element.matches(':focus-visible'),focused:document.activeElement===element,rect:{x:r.x,y:r.y,width:r.width,height:r.height}}});
async function textSample(page,row,name,state){const observed=await style(page.locator(primarySelector));row.states.push({state,style:observed});assert.equal(observed.hover,state!=='default');assert.equal(observed.active,state==='active');const measured=await actualTextContrast(page,out,name+'-'+state,[['primary',primarySelector]]);row.states.at(-1).analysis=measured.analysis;row.states.at(-1).input=measured.input;row.states.at(-1).output=measured.output;report.pngs.push(...measured.pngs);const after=await style(page.locator(primarySelector));row.states.at(-1).styleAfter=after;for(const key of ['color','backgroundColor','boxShadow','hover','active'])assert.equal(after[key],observed[key],'Capture preserved '+state+' '+key);assert.equal(measured.analysis.pass,true,name+' '+state+' actual text contrast');check(name+' '+state+' text contrast',{minRatio:Math.min(...measured.analysis.regions.flatMap(region=>region.runs.map(run=>run.actualGlyphMinRatio)))})}
try{
 report.hashesBefore=verify();report.helpersBefore=['states.mjs','contrast-capture.mjs','contrast_pixels.py','focus-capture.mjs','fixture.mjs'].map(file=>fingerprint(root+'/'+file));
 browser=await chromium.launch({executablePath:'/usr/bin/chromium'});
 for(const width of [1440,390,320]){const c=await open(width),{page}=c,name='en-light-'+width,row={width,locale:'en',theme:'light',states:[],focus:[]};report.cases.push(row);
  try{
   await page.goto(base+'#/');await page.locator('#landing-title').waitFor();await page.evaluate(()=>document.fonts.ready);const photo=await page.locator('.oda-landing-hero-photo img').evaluate(async image=>{await image.decode();return{source:image.currentSrc,complete:image.complete,naturalWidth:image.naturalWidth,naturalHeight:image.naturalHeight}});await page.waitForTimeout(250);await Promise.all(pending);row.photo=photo;
   assert.equal(await page.locator('.oda-landing').getAttribute('lang'),'en');assert.equal(await page.evaluate(()=>document.documentElement.getAttribute('data-theme')),'light');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),width);assert.equal(photo.complete,true);assert.ok(photo.naturalWidth>0);const expected=width===1440?'hero-dolomites-1920.webp':'hero-dolomites-mobile-480.webp';assert.ok(photo.source.endsWith(expected));assert.equal(c.requests.filter(item=>item.url.includes('/assets/oda/landing-photo/')).length,1);assert.equal(c.rows.filter(item=>item.file.endsWith(expected)).length,1);check(name+' exact approved photo served',{photo:expected});
   const primary=page.locator(primarySelector);await page.mouse.move(0,0);
   if(width===1440){row.states=reuse1440.states;row.focus=[reuse1440.focus.find(item=>item.label==='primary')];row.reusedFrom=path.dirname(reusePath);report.pngs.push(...reuse.pngs.map(item=>({...item,path:path.join(path.dirname(reusePath),item.file),reused:true})));check(name+' passed CTA states and primary focus retained from sealed attempt-2')}
   else{await primary.scrollIntoViewIfNeeded();await page.waitForTimeout(220);await textSample(page,row,name,'default');await primary.hover();await page.waitForTimeout(220);await textSample(page,row,name,'hover');await page.mouse.down();try{await page.waitForTimeout(220);await textSample(page,row,name,'active')}finally{await page.mouse.move(0,0);await page.mouse.up()}assert.equal(new URL(page.url()).hash,'#/','Release off CTA must avoid navigation')}
   await page.keyboard.press('Tab');
   for(const [label,selector,regionSelector] of [['primary',primarySelector,'.oda-landing-hero'],['nav-open',navSelector,'.oda-landing-nav']].filter(item=>width!==1440||item[0]!=='primary')){const control=page.locator(selector);await control.focus();await control.scrollIntoViewIfNeeded();await page.waitForTimeout(80);const observed=await style(control);assert.equal(observed.focused,true);assert.equal(observed.focusVisible,true);assert.ok(observed.rect.width>=44&&observed.rect.height>=44,'Focus control 44px target');const measured=await actualFocusContrast(page,out,name+'-'+label,selector,regionSelector);row.focus.push({label,selector,style:observed,...measured});report.pngs.push(...measured.pngs);assert.equal(measured.analysis.pass,true,name+' '+label+' actual outline contrast');check(name+' '+label+' keyboard focus outline',{minRatio:measured.analysis.actualOutlineMinRatio,width:measured.outline.width,offset:measured.outline.offset})}
   await Promise.all(pending);assert.equal(report.pageErrors.length,0);assert.equal(report.responseErrors.length,0);check(name+' scoped CTA and focus states complete');
  }finally{await Promise.all(pending);await c.context.close()}
 }
 report.hashesAfter=verify();report.helpersAfter=report.helpersBefore.map(item=>fingerprint(item.file));assert.deepEqual(report.helpersAfter,report.helpersBefore,'QA helper files stayed unchanged');assert.equal(report.pageErrors.length,0);assert.equal(report.responseErrors.length,0);report.pass=true;
}catch(error){report.error={name:error.name,message:error.message,stack:error.stack,classification:'pending evidence review'};console.error(JSON.stringify({firstAttemptFailure:report.error,report:out+'/report.json'}));throw error
}finally{
 if(browser)try{await browser.close()}catch(error){report.browserCloseError={message:error.message};report.pass=false}try{report.hashesAfter=verify()}catch(error){report.freezeError={message:error.message};report.pass=false}report.finishedAtUtc=new Date().toISOString();
 report.allPngs=fs.readdirSync(out).filter(file=>file.endsWith('.png')).map(file=>fingerprint(out+'/'+file));fs.writeFileSync(out+'/report.json',JSON.stringify(report,null,2)+'\n');
 const evidence=fs.readdirSync(out).filter(file=>file!=='seal.json').map(file=>fingerprint(out+'/'+file));const seal={sourceCommit:expectedCommit,receiptPath,receiptSha256:expectedReceiptSha,attempt:next,pass:report.pass,published:false,scope:report.scope,evidence};fs.writeFileSync(out+'/seal.json',JSON.stringify(seal,null,2)+'\n');fs.writeFileSync(statesRoot+'/latest.json',JSON.stringify({attempt:next,pass:report.pass,report:out+'/report.json',seal:out+'/seal.json'},null,2)+'\n');console.log(JSON.stringify({pass:report.pass,report:out+'/report.json',seal:out+'/seal.json',cases:report.cases.length,pngs:report.allPngs.length}));
}
