import fs from 'node:fs';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import {chromium} from '/workspace/oda-landing-photographic/node_modules/playwright/index.mjs';
import AxeBuilder from '/workspace/oda-landing-photographic/node_modules/@axe-core/playwright/dist/index.mjs';
import {makeSeed} from './fixture.mjs';
import {actualTextContrast} from './contrast-capture.mjs';

// Preparation only until the parent supplies an exact frozen build and approved photo paths.
if(process.env.ODA_LANDING_QA_GO!=='1'||!process.env.ODA_BUILD_RECEIPT||!process.env.ODA_PHOTO_PATHS)throw Error('Parent frozen-source/build GO, build receipt and approved local photo paths required');
const repo='/workspace/oda-landing-photographic',root='/workspace/scratch/oda-landing-photographic/browser-qa';
const base=process.env.ODA_QA_URL||'http://127.0.0.1:4195/one-decision-away/';
const origin=new URL(base);assert.equal(origin.protocol,'http:');assert.ok(['127.0.0.1','localhost'].includes(origin.hostname),'Local ordinary preview only');
const receipt=JSON.parse(fs.readFileSync(process.env.ODA_BUILD_RECEIPT)),baseline=JSON.parse(fs.readFileSync(root+'/baseline-index.json'));
const out=root+'/final';fs.mkdirSync(out,{recursive:true});
const sha=b=>createHash('sha256').update(b).digest('hex');
const sealBytes=fs.readFileSync(baseline.priorSeal.path);assert.equal(sealBytes.length,baseline.priorSeal.bytes);assert.equal(sha(sealBytes),baseline.priorSeal.sha256);
const priorSeal=JSON.parse(sealBytes),priorReportBytes=fs.readFileSync(baseline.captureDirectory+'/report.json'),priorReportSpec=priorSeal.supportingEvidence.find(x=>x.file==='final/report.json');assert.equal(priorReportBytes.length,priorReportSpec.bytes);assert.equal(sha(priorReportBytes),priorReportSpec.sha256);
const priorReport=JSON.parse(priorReportBytes);assert.equal(baseline.cases.length,9);for(const c of baseline.cases){const sealed=priorReport.cases.find(x=>x.route===c.route&&x.width===c.width);assert.deepEqual(c,sealed);for(const p of c.pngs){const b=fs.readFileSync(baseline.captureDirectory+'/'+p.file);assert.equal(b.length,p.bytes);assert.equal(sha(b),p.sha256)}}
const relative=url=>new URL(url,base).pathname.slice(origin.pathname.length)||'index.html';
const photoPaths=process.env.ODA_PHOTO_PATHS.split(',').map(x=>x.trim().replace(/^dist\//,'').replace(/^\//,''));
const maxInitialPhotoBytes=process.env.ODA_MAX_INITIAL_PHOTO_BYTES?Number(process.env.ODA_MAX_INITIAL_PHOTO_BYTES):null;
function verify(){for(const a of [...receipt.source,...receipt.build]){const b=fs.readFileSync(repo+'/'+a.file);assert.equal(b.length,a.bytes,a.file);assert.equal(sha(b),a.sha256,a.file)}return{source:receipt.source.length,compiled:receipt.build.length}}
for(const p of photoPaths)assert.ok(receipt.build.some(x=>x.file==='dist/'+p),'Approved photo exists in exact build: '+p);
const report={sourceCommit:receipt.sourceCommit,checkoutHead:execFileSync('git',['rev-parse','HEAD'],{cwd:repo,encoding:'utf8'}).trim(),receiptPath:process.env.ODA_BUILD_RECEIPT,startedAtUtc:new Date().toISOString(),hashesBefore:verify(),base,synthetic:true,physicalDevice:false,published:false,photoPaths,maxInitialPhotoBytes,cases:[],checks:[],pngs:[],contrast:[],servedResponses:[],externalBlocked:[],pageErrors:[],responseErrors:[],protectedComparisons:[],renderedTextContrast:[]};
const pass=(name,detail={})=>report.checks.push({name,pass:true,...detail}),pending=[];
const browser=await chromium.launch({executablePath:'/usr/bin/chromium'});
async function open(width,locale='en',theme='light'){
 const context=await browser.newContext({viewport:{width,height:width===1440?1000:844},locale:({en:'en-US',tr:'tr-TR',es:'es-ES'})[locale],timezoneId:'UTC',colorScheme:theme,reducedMotion:'reduce',serviceWorkers:'block'});
 await context.route('**/*',r=>{const u=new URL(r.request().url());if(u.origin===origin.origin&&u.pathname.startsWith(origin.pathname)&&r.request().method()==='GET')return r.continue();report.externalBlocked.push({method:r.request().method(),url:u.origin+u.pathname});return r.abort()});
 const seed=makeSeed();Object.assign(seed.profile,{locale,theme});
 await context.addInitScript(({seed,locale,theme})=>{
  localStorage.setItem('one_decision_away_app_data_v1',JSON.stringify(seed));localStorage.setItem('oda_locale',locale);localStorage.setItem('oda_theme',theme);
  window.__qaWrites=[];
  for(const name of ['put','add','delete','clear']){const original=IDBObjectStore.prototype[name];IDBObjectStore.prototype[name]=function(...args){window.__qaWrites.push({kind:'idb',name,store:this.name});return original.apply(this,args)}}
  for(const name of ['setItem','removeItem','clear']){const original=Storage.prototype[name];Storage.prototype[name]=function(...args){if(this===localStorage)window.__qaWrites.push({kind:'localStorage',name,key:args[0]||null});return original.apply(this,args)}}
 },{seed,locale,theme});
 const page=await context.newPage();await page.clock.setFixedTime(new Date('2026-10-03T12:00:00.000Z'));
 const rows=[],requests=[];context.on('request',r=>requests.push({url:r.url(),method:r.method()}));page.on('pageerror',e=>report.pageErrors.push(e.message));
 page.on('response',response=>{const u=new URL(response.url());if(u.origin!==origin.origin)return;const rel=relative(response.url());const asset=receipt.build.find(a=>a.file==='dist/'+rel);if(!asset)return;pending.push((async()=>{const b=await response.body();const row={url:response.url(),file:asset.file,status:response.status(),bytes:b.length,sha256:sha(b)};assert.equal(row.status,200,'HTTP '+rel);assert.equal(row.bytes,asset.bytes,'HTTP '+rel);assert.equal(row.sha256,asset.sha256,'HTTP '+rel);rows.push(row);report.servedResponses.push(row)})().catch(e=>report.responseErrors.push(e.message)))});
 return{context,page,rows,requests};
}
async function ready(page,selector){await page.locator(selector).waitFor();await page.evaluate(()=>document.fonts.ready);await page.evaluate(async()=>{await Promise.all([...document.images].filter(e=>{const r=e.getBoundingClientRect();return r.width>0&&r.bottom>0&&r.top<innerHeight}).map(e=>e.decode().catch(()=>{})))});await page.waitForTimeout(250);await Promise.all(pending)}
async function capture(page,file,fullPage=false){await page.screenshot({path:out+'/'+file,fullPage,animations:'disabled'});const b=fs.readFileSync(out+'/'+file);report.pngs.push({file,bytes:b.length,sha256:sha(b)})}
async function view(page){return page.evaluate(()=>({width:innerWidth,height:innerHeight,scrollWidth:document.documentElement.scrollWidth,bodyWidth:document.body.scrollWidth,theme:document.documentElement.getAttribute('data-theme'),lang:document.querySelector('.oda-landing')?.getAttribute('lang')}))}
async function photos(page,decodeBackground=false){return page.evaluate(async ({paths,decodeBackground})=>{
 const rect=e=>{const r=e.getBoundingClientRect();return{x:r.x,y:r.y,width:r.width,height:r.height,top:r.top,bottom:r.bottom}};
 const approved=url=>paths.some(p=>new URL(url,location.href).pathname.endsWith('/'+p));
 const images=[...document.querySelectorAll('.oda-landing img')].filter(e=>approved(e.currentSrc||e.src));
 const items=images.map(e=>({kind:'img',source:e.currentSrc||e.src,srcset:e.srcset,alt:e.alt,loading:e.loading,decoding:e.decoding,complete:e.complete,naturalWidth:e.naturalWidth,naturalHeight:e.naturalHeight,rect:rect(e),objectFit:getComputedStyle(e).objectFit,objectPosition:getComputedStyle(e).objectPosition,pictureSources:[...e.closest('picture')?.querySelectorAll('source')||[]].map(s=>({media:s.media,type:s.type,srcset:s.srcset}))}));
 for(const e of document.querySelectorAll('.oda-landing, .oda-landing *'))for(const pseudo of [null,'::before','::after']){const c=getComputedStyle(e,pseudo);for(const m of c.backgroundImage.matchAll(/url\(["']?([^"')]+)["']?\)/g)){if(!approved(m[1]))continue;let image=null;if(decodeBackground){image=new Image();image.src=m[1];await image.decode()}items.push({kind:'background',source:new URL(m[1],location.href).href,pseudo,diagnosticDecode:decodeBackground,complete:image?.complete??null,naturalWidth:image?.naturalWidth??null,naturalHeight:image?.naturalHeight??null,rect:rect(e),backgroundSize:c.backgroundSize,backgroundPosition:c.backgroundPosition})}}
 return items;
 },{paths:photoPaths,decodeBackground})}
const storageState=page=>page.evaluate(()=>({storage:Object.fromEntries(Object.entries(localStorage)),writes:window.__qaWrites.length}));
async function landingControls(page,name){
 await page.evaluate(()=>window.scrollTo(0,0));await page.keyboard.press('Tab');assert.equal(await page.evaluate(()=>document.activeElement.classList.contains('oda-landing-skip')),true);const skip=await page.locator('.oda-landing-skip').boundingBox();assert.ok(skip&&skip.y>=0);await capture(page,name+'-keyboard-skip.png');await page.keyboard.press('Enter');assert.equal(await page.evaluate(()=>document.activeElement.id),'oda-landing-main');pass(name+' keyboard skip reaches main');
 const controls=page.locator('.oda-landing-preview-controls button');assert.equal(await controls.count(),3);const before=await storageState(page);const titles=[];for(let i=0;i<3;i++){await controls.nth(i).focus();await page.keyboard.press(i===1?'Enter':'Space');assert.equal(await controls.nth(i).getAttribute('aria-pressed'),'true');titles.push(await page.locator('.oda-landing-preview-title').innerText())}assert.equal(new Set(titles).size,3);await controls.first().click();await page.waitForTimeout(50);assert.deepEqual(await storageState(page),before);pass(name+' sample changes all three steps and resets without personal/native storage writes');
 const faq=page.locator('.oda-landing-faq summary').first();await faq.focus();await page.keyboard.press('Enter');assert.equal(await faq.evaluate(e=>e.parentElement.open),true);await page.keyboard.press('Enter');assert.equal(await faq.evaluate(e=>e.parentElement.open),false);pass(name+' FAQ keyboard toggle');
 const primary=page.locator('.oda-landing-hero-actions .oda-landing-button-primary');await primary.focus();const focus=await primary.evaluate(e=>{const c=getComputedStyle(e),r=e.getBoundingClientRect();return{outline:c.outlineStyle,width:c.outlineWidth,color:c.outlineColor,height:r.height,visible:e.matches(':focus-visible')}});assert.ok(focus.height>=44);assert.equal(focus.visible,true);assert.notEqual(focus.outline,'none');pass(name+' visible CTA keyboard focus and 44px target',{focus});
}
const protectedSelectors=['.oda-sidebar','.oda-sidebar>button:first-child','.oda-sidebar-profile','.oda-reference-app>header','.oda-reference-app','.oda-page-enter','.oda-fidelity-hero','.oda-decision','.oda-decision-text','.oda-decision-action','.oda-hybrid-progress','.oda-hybrid-actions','.oda-growth-panel','.oda-growth-course','.oda-tabbar','#notebook-journal-content','#coach-message'];
async function protectedNodes(page){return page.evaluate(selectors=>{const rect=e=>{const r=e.getBoundingClientRect();return{x:r.x,y:r.y,width:r.width,height:r.height,right:r.right,bottom:r.bottom}};const style=e=>{const c=getComputedStyle(e);return{color:c.color,bg:c.backgroundColor,image:c.backgroundImage,display:c.display,padding:c.padding,border:c.borderColor,font:c.fontFamily,fontSize:c.fontSize,fontWeight:c.fontWeight,outline:c.outlineColor,outlineWidth:c.outlineWidth}};return Object.fromEntries(selectors.map(s=>[s,[...document.querySelectorAll(s)].map(e=>({rect:rect(e),style:style(e),text:e.textContent.trim().slice(0,200)}))]))},protectedSelectors)}
try{
 const matrix=[...[1440,390,320].map(width=>({width,locale:'en',theme:'light'})),...[1440,390,320].flatMap(width=>['en','tr','es'].flatMap(locale=>['light','dark'].filter(theme=>locale!=='en'||theme!=='light').map(theme=>({width,locale,theme}))))];
 report.resume={from:'attempt-1/final/report.json',reason:'Normal element screenshot blank below-viewport strip; paired capture changed to full-document clip. Completed EN/light1440 and390 retained without rerun.'};
 for(const {width,locale,theme} of matrix.filter((c,i)=>process.env.ODA_QA_RESUME!=='1'||i>=2)){
  const c=await open(width,locale,theme),page=c.page,name=`landing-${locale}-${theme}-${width}`;try{
   await page.goto(base+'#/');await ready(page,'#landing-title');const observed=await view(page);assert.equal(observed.scrollWidth,width);assert.equal(observed.lang,locale);assert.equal(observed.theme,theme);const initialPhotos=await photos(page);await Promise.all(pending);assert.ok(initialPhotos.length>0,'Approved real photo must render');assert.ok(initialPhotos.filter(x=>x.rect.width>0&&x.rect.top<observed.height).every(x=>x.kind==='background'?c.rows.some(r=>r.url===x.source):x.complete&&x.naturalWidth>0),'Visible approved photos decoded or actual CSS background bytes served');const initialPhotoBytes=c.rows.filter(x=>photoPaths.includes(relative(x.url))).reduce((sum,x)=>sum+x.bytes,0);if(maxInitialPhotoBytes!==null)assert.ok(initialPhotoBytes<=maxInitialPhotoBytes);await capture(page,name+'.png');const photoRequests=c.requests.filter(r=>r.url.includes('/assets/oda/landing-photo/'));assert.equal(photoRequests.length,1,'Single selected/preloaded photo request '+name);assert.equal(c.rows.filter(r=>r.url.includes('/assets/oda/landing-photo/')).length,1);const expectedPhoto=width===1440?'hero-dolomites-1920.webp':'hero-dolomites-mobile-480.webp';assert.ok(initialPhotos.some(p=>p.source.endsWith(expectedPhoto)));assert.equal(initialPhotoBytes,width===1440?130032:34224);assert.ok(!c.requests.some(r=>r.url.includes('oda-hero-wolfgang-moritzer-original')||r.url.endsWith('.jpg')));pass(name+' one exact chosen derivative, no duplicate/preload or original download',{photoRequests,initialPhotoBytes});
   if(theme==='light'||locale==='en'&&width===390){const measured=await actualTextContrast(page,out,name);report.renderedTextContrast.push({name,input:measured.input,output:measured.output,result:measured.analysis});report.pngs.push(...measured.pngs);assert.equal(measured.analysis.pass,true,'Actual composed-background text contrast '+name);pass(name+' actual rendered photograph/scrim text contrast')}
   await page.evaluate(()=>window.scrollTo(0,0));
   for(const section of await page.locator('.oda-landing main section').all()){await section.scrollIntoViewIfNeeded();await ready(page,'#landing-title')}await page.evaluate(()=>window.scrollTo(0,0));const allPhotos=await photos(page,true);await Promise.all(pending);assert.ok(allPhotos.filter(x=>x.rect.width>0).every(x=>x.complete&&x.naturalWidth>0),'Rendered approved photos decode after ordinary section scrolling');if(locale==='en'&&theme==='light')await capture(page,name+'-full.png',true);report.cases.push({width,locale,theme,observed,initialPhotoBytes,initialPhotos,allPhotos});pass(name+' localized/theme layout has no horizontal overflow and actual photos load');
   for(const node of await page.locator('.oda-landing-hero-actions button,.oda-landing-preview-controls button,.oda-landing-nav-actions button').all()){const r=await node.boundingBox();if(r)assert.ok(r.height>=44,'Primary visible control height')}pass(name+' primary visible 44px controls');
   if(width===390)await landingControls(page,name);
   if(width===1440&&locale==='en'&&theme==='light'){for(const [index,target] of [[0,'oda-method'],[1,'oda-discover']]){await page.locator('.oda-landing-nav-link').nth(index).click();assert.equal(await page.evaluate(()=>document.activeElement.id),target)}pass('Desktop method/course navigation scrolls and focuses actual sections')}
   if(locale==='en'&&theme==='light'||width===390&&(theme==='dark'&&locale==='en'||theme==='light')){const a=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21a','wcag21aa']).analyze();const compact={name,violations:a.violations.map(v=>({id:v.id,impact:v.impact,targets:v.nodes.map(n=>n.target)})),incomplete:a.incomplete.map(v=>({id:v.id,targets:v.nodes.map(n=>n.target)}))};report.contrast.push(compact);assert.equal(compact.violations.length,0,'Scoped axe '+name);pass(name+' scoped WCAG audit zero reported violations')}
  }finally{await Promise.all(pending);await c.context.close()}
 }
 // Protected pages use the already sealed prior baseline; no baseline campaign rerun.
 for(const before of baseline.cases){const c=await open(before.width),page=c.page;try{await page.goto(base+'#/app'+(before.route==='today'?'':'/'+before.route));await ready(page,before.route==='today'?'.oda-decision-text':before.route==='notebook'?'#notebook-journal-content':'#coach-message');const after=await protectedNodes(page),differences=[];assert.equal(await page.locator('link[rel=preload][as=image]').evaluateAll(es=>es.filter(e=>e.href.includes('/assets/oda/landing-photo/')).length),0,'No landing photo preloads on direct app route');assert.equal(c.requests.filter(r=>r.url.includes('/assets/oda/landing-photo/')).length,0,'No landing photo request on direct app route');for(const selector of protectedSelectors){if(JSON.stringify(after[selector])!==JSON.stringify(before.observed.nodes[selector]))differences.push(selector)}report.protectedComparisons.push({route:before.route,width:before.width,differences});assert.deepEqual(differences,[],'Protected '+before.route+' '+before.width);assert.equal((await view(page)).scrollWidth,before.width);await capture(page,`protected-${before.route}-${before.width}.png`);pass('Protected '+before.route+' '+before.width+' geometry/text/styles match sealed baseline')}finally{await Promise.all(pending);await c.context.close()}}
 // Existing real navigation is exercised in synthetic local contexts only.
 const c=await open(390),page=c.page;try{
  for(const [selector,index,route,target] of [['.oda-landing-hero-actions .oda-landing-button-primary',0,'/app','.oda-decision-text'],['.oda-landing-course button',0,'/app/courses','.oda-course-lesson-title,[data-course-overview] .oda-course-title'],['.oda-landing-resource',0,'/app/notebook','#notebook-journal-content'],['.oda-landing-resource',1,'/app/dreams','.oda-page-enter'],['.oda-landing-resource',2,'/app/focus','#focus-timer-hub'],['.oda-landing-resource',3,'/app/coach','#coach-message'],['.oda-landing-legal button',0,'/privacy','header h1'],['.oda-landing-legal button',1,'/terms','header h1']]){await page.goto(base+'#/');await ready(page,'#landing-title');const expectedCourseTitle=route==='/app/courses'?await page.locator('.oda-landing-course h3').first().innerText():null;await page.locator(selector).nth(index).click();await page.waitForFunction(route=>location.hash==='#'+route,route);await page.locator(target).waitFor();const retainedPhotoHints=await page.locator('link[rel=preload][as=image]').evaluateAll(es=>es.filter(e=>e.href.includes('/assets/oda/landing-photo/')).map(e=>({href:e.href,media:e.media})));report.checks.push({name:'React resource-hint observation after '+route,pass:true,retainedPhotoHints,note:'Hoisted React19 hints can persist after landing; direct app route isolation checked separately.'});if(expectedCourseTitle!==null)assert.equal(await page.locator('.oda-course-lesson-header .oda-course-eyebrow span,[data-course-overview] #course-overview-title').innerText(),expectedCourseTitle);pass('Landing existing navigation reaches '+route)}
  await page.goto(base+'#/');await ready(page,'#landing-title');for(const locale of ['tr','es','en']){await page.locator('.oda-landing-nav select').selectOption(locale);await page.waitForFunction(locale=>document.querySelector('.oda-landing')?.getAttribute('lang')===locale,locale)}pass('Existing language picker switches EN/TR/ES');
 }finally{await Promise.all(pending);await c.context.close()}
 await Promise.all(pending);assert.deepEqual(report.responseErrors,[]);assert.deepEqual(report.pageErrors,[]);assert.equal(report.servedResponses.filter(x=>x.file.endsWith('.mp3')).length,0);pass('No browser errors or automatic narration download');report.hashesAfter=verify();report.finishedAtUtc=new Date().toISOString();
}catch(e){report.error={name:e.name,message:e.message,stack:e.stack};throw e}finally{await browser.close();fs.writeFileSync(out+'/report.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({sourceCommit:report.sourceCommit,cases:report.cases.length,pngs:report.pngs.length,checks:report.checks.length,error:report.error}))}
