/** Lightweight metadata for first use. Regenerate after editing course structure. */
import { writeFileSync } from 'node:fs';
import { coursesFor } from '../src/data/courses';

const editions = Object.fromEntries(['en', 'tr', 'es'].map(locale => [locale, coursesFor(locale).map(course => ({
  id: course.id, lang: course.lang, title: course.title, subtitle: course.subtitle,
  description: course.description, outcome: course.outcome,
  minutes: course.lessons.reduce((total, lesson) => total + lesson.minutes, 0),
  lessonCount: course.lessons.length, lessonIds: course.lessons.map(lesson => lesson.id),
  lessons: course.lessons.map(lesson => ({ id: lesson.id, practiceCount: lesson.practice.length, optionCount: lesson.options.length, correct: lesson.correct })),
}))]));
writeFileSync('src/data/courseCatalog.ts', `/** Generated by scripts/build-course-catalog.ts. Keep full lesson text off the first-use path. */\nconst EDITIONS = ${JSON.stringify(editions, null, 2)};\n\nexport type CourseCatalogEntry = (typeof EDITIONS.en)[number];\nexport function courseCatalogFor(locale: string): CourseCatalogEntry[] {\n  return locale === 'tr' ? EDITIONS.tr : locale === 'es' ? EDITIONS.es : EDITIONS.en;\n}\n`);
