import fs from 'node:fs';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {chromium} from '/workspace/oda-reference-redesign/node_modules/playwright/index.mjs';
import {getInitialDemoState} from '/workspace/oda-reference-redesign/src/services/repository.ts';
import {coursesFor} from '/workspace/oda-reference-redesign/src/data/courses.ts';
import {makeSeed} from '../../domino-palette/browser-qa/fixture.mjs';

if(process.env.ODA_FINAL_QA_GO!=='1'||!process.env.ODA_BUILD_RECEIPT)throw Error('Frozen-source rootGO and receipt required');
const root='/workspace/scratch/oda-reference-redesign/domino-logo/browser-qa',repo='/workspace/oda-reference-redesign',receipt=JSON.parse(fs.readFileSync(process.env.ODA_BUILD_RECEIPT));
const out=root+'/'+(process.env.ODA_QA_MODE||'final')+'/continuity';fs.mkdirSync(out,{recursive:true});
const sha=b=>createHash('sha256').update(b).digest('hex');
function verify(){for(const a of [...receipt.source,...receipt.build]){const b=fs.readFileSync(repo+'/'+a.file);assert.equal(sha(b),a.sha256,a.file)}return{source:receipt.source.length,compiled:receipt.build.length}}
const report={sourceCommit:receipt.sourceCommit,hashesBefore:verify(),synthetic:true,physicalDevice:false,checks:[],screenshots:[],mp3:[],servedResponses:[],externalBlocked:[],pageErrors:[],startedAtUtc:new Date().toISOString()};
const pass=(name,data={})=>report.checks.push({name,pass:true,...data});
const base='http://127.0.0.1:4194/one-decision-away/',pending=[],browser=await chromium.launch({executablePath:'/usr/bin/chromium'});
async function open(seed,width=390,draft=null){
 const context=await browser.newContext({viewport:{width,height:width===1440?1000:844},timezoneId:'UTC',locale:'en-US',reducedMotion:'reduce',serviceWorkers:'block'});
 await context.route('**/*',r=>{let u=new URL(r.request().url());if(u.origin===new URL(base).origin)return r.continue();report.externalBlocked.push(u.origin+u.pathname);return r.abort()});
 await context.addInitScript(({seed,draft})=>{localStorage.setItem('one_decision_away_app_data_v1',JSON.stringify(seed));localStorage.setItem('oda_locale','en');localStorage.setItem('oda_theme','light');localStorage.setItem('oda_voice_prefs',JSON.stringify({enabled:true,volume:.65,engine:'browser'}));if(draft)localStorage.setItem('oda_onboarding_draft_v1',JSON.stringify(draft))},{seed,draft});
 const page=await context.newPage();page.on('pageerror',e=>report.pageErrors.push(e.message));page.on('response',r=>{const u=new URL(r.url());if(u.origin!==new URL(base).origin)return;const rel=u.pathname.slice('/one-decision-away/'.length)||'index.html';const a=receipt.build.find(x=>x.file==='dist/'+rel);if(a&&(/\.(js|css|mp3)$/.test(rel)||rel==='index.html'))pending.push((async()=>{const b=await r.body();assert.equal(sha(b),a.sha256,'HTTP '+rel);const entry={file:a.file,bytes:b.length,sha256:sha(b),status:r.status()};report.servedResponses.push(entry);if(rel.endsWith('.mp3'))report.mp3.push(entry)})())});return{page,context};
}
async function screenshot(page,name){await page.evaluate(()=>document.fonts.ready);const file=name+'.png';await page.screenshot({path:out+'/'+file,animations:'disabled'});const b=fs.readFileSync(out+'/'+file);report.screenshots.push({file,bytes:b.length,sha256:sha(b)})}
const read=p=>p.evaluate(()=>JSON.parse(localStorage.getItem('one_decision_away_app_data_v1')));
async function waitRecord(p,predicate){for(let i=0;i<80;i++){const d=await read(p);if(predicate(d))return d;await p.waitForTimeout(50)}throw Error('Synthetic native write did not settle')}
try{
 // First-use continuation: preview state never credits a kept decision or reward.
 for(const preserved of [false,true]){const seed=getInitialDemoState();Object.assign(seed.profile,{locale:'en',theme:'light',soundMuted:true,nudgesEnabled:false,dailyWisdomEnabled:false});const draft=preserved?{version:1,step:0,name:'Alex',intent:null,dreamId:null,decision:'Keep my original plan.'}:null;const c=await open(seed,320,draft),p=c.page;try{
  await p.goto(base+'#/app');await p.locator('[data-onboarding-preview="pick"]').waitFor();assert.match(await p.locator('.oda-onboarding').innerText(),/Preview · sample only/);await p.getByRole('button',{name:'Walk for 2 minutes',exact:true}).click();const projection=await read(p);assert.equal(projection.completions.length,0);assert.equal(projection.transactions.filter(t=>t.kind==='one_decision_reward').length,0);pass('Onboarding preview is labelled and credits no kept decision/reward '+preserved);
  await p.getByRole('button',{name:'Continue',exact:true}).click();await p.locator('#onboarding-name').fill('Alex');await p.getByRole('button',{name:'Continue',exact:true}).click();await p.getByRole('button',{name:'Skip for now',exact:true}).click();await p.getByRole('button',{name:'Skip for now',exact:true}).click();await p.locator('#onboarding-decision').waitFor();assert.equal(await p.locator('#onboarding-decision').inputValue(),preserved?'Keep my original plan.':'Walk for 2 minutes');pass('Chosen demo decision continues only without an existing saved draft '+preserved);await screenshot(p,preserved?'onboarding-protected-draft-320':'onboarding-preview-carried-320');
 }finally{await c.context.close()}}
 // Read, search, overview and resume are real existing course flows.
 const c=await open(makeSeed(),1440),p=c.page;try{
  await p.goto(base+'#/app');await p.locator('.oda-decision-text').waitFor();const next=coursesFor('en').find(x=>x.id==='turning-day').lessons[1];assert.match(await p.locator('.oda-course-next-step').innerText(),new RegExp(next.title.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));pass('Today continuation exposes actual next lesson title/minutes');
  await p.goto(base+'#/app/courses');await p.locator('#course-search').waitFor();await p.locator('#course-search').fill('confidence');const untouched=p.locator('[data-course-id="confidence"]');await untouched.waitFor();const expectedSearch=coursesFor('en').filter(item=>`${item.title} ${item.subtitle} ${item.description}`.toLowerCase().includes('confidence')).map(item=>item.id).sort();assert.deepEqual((await p.locator('.oda-course-row').evaluateAll(es=>es.map(e=>e.getAttribute('data-course-id')))).sort(),expectedSearch);pass('Course catalogue search remains functional');await untouched.click();await p.locator('[data-course-overview="confidence"]').waitFor();const course=coursesFor('en').find(x=>x.id==='confidence'),text=await p.locator('[data-course-overview="confidence"]').innerText();assert.ok(text.includes(course.description));assert.ok(text.includes(course.outcome));assert.ok(text.includes(course.lessons[0].title));assert.match(await p.locator('#course-start-lesson').innerText(),/Start lesson 1/);pass('Untouched course opens real description/outcome/lesson overview');await screenshot(p,'untouched-course-overview-1440');await p.locator('#course-start-lesson').click();await p.locator('.oda-course-lesson-title').waitFor();assert.equal(await p.locator('.oda-course-lesson-title').innerText(),course.lessons[0].title);assert.ok(await p.locator('.oda-course-quiz input[type="radio"]').count()>0);assert.ok(await p.locator('.oda-course-practice input[type="checkbox"]').count()>0);pass('Start lesson1 retains actual lesson practice and quiz');
  await p.getByRole('button',{name:'All courses',exact:true}).first().click();await p.locator('.oda-course-resume').waitFor();await p.locator('.oda-course-resume').getByRole('button',{name:'Continue',exact:true}).click();await p.locator('.oda-course-lesson-title').waitFor();assert.equal(await p.locator('.oda-course-lesson-title').innerText(),next.title);pass('Returning TurningPointDay learner resumes saved lesson2');await screenshot(p,'course-resumed-lesson2-1440');
  await p.goto(base+'#/app/notebook');await p.locator('#notebook-journal-content').waitFor();await p.locator('#notebook-journal-title').fill('A quiet moment');await p.locator('#notebook-journal-content').fill('I took a short walk and gave myself time to think.');await p.goto(base+'#/app');await p.locator('.oda-decision-text').waitFor();await p.goto(base+'#/app/notebook');await p.locator('#notebook-journal-content').waitFor();assert.equal(await p.locator('#notebook-journal-content').inputValue(),'I took a short walk and gave myself time to think.');assert.equal(await p.locator('#notebook-journal-title').inputValue(),'A quiet moment');pass('Notebook unsaved draft survives route leave/return');await p.getByRole('button',{name:'Save entry',exact:true}).click();const saved=await waitRecord(p,d=>d.notebook.entries.some(e=>e.title==='A quiet moment'));assert.equal(saved.notebook.entries.filter(e=>e.title==='A quiet moment').length,1);assert.ok(saved.notebook.entries.some(e=>e.title==='A small step forward'));pass('Notebook save adds one entry and preserves earlier saved entry');await screenshot(p,'notebook-saved-continuity-1440');
 }finally{await c.context.close()}
 // Actual approved MP3 decoder playback, bounded first/current/upcoming load and cache replay.
 const audio=await open(makeSeed()),q=audio.page;try{
  await q.goto(base+'#/app/focus');await q.locator('#focus-timer-hub').waitFor();await q.getByRole('button',{name:'Guided',exact:true}).click();const first=q.locator('[data-guided-session]').first(),sessionId=await first.getAttribute('data-guided-session');const preview=first.getByRole('button',{name:/^Preview voice:/});assert.equal(await preview.locator('svg').count(),1);await Promise.all(pending);assert.equal(report.mp3.length,0);pass('Guidance page fetches no MP3 before explicit playback and exposes speaker Preview voice');await preview.click();await q.locator('[data-guidance-mode="recorded"]').waitFor();await Promise.all(pending);assert.equal(report.mp3.length,1);assert.ok(report.mp3[0].file.includes('/en-US/v1/clips/'+sessionId+'-00.'));pass('Preview actually plays one exact approved English current clip',{mp3:report.mp3.slice()});await screenshot(q,'recorded-english-preview-390');await first.getByRole('button',{name:/^Stop voice preview:/}).click();
  await first.getByRole('button',{name:/^Start:/}).click();await q.getByRole('button',{name:'Pause',exact:true}).waitFor();await q.waitForTimeout(300);await Promise.all(pending);const unique=[...new Set(report.mp3.map(x=>x.file))];assert.ok(unique.length>=2&&unique.length<=3);assert.ok(report.mp3.every(x=>x.file.includes('/en-US/v1/')));assert.ok(report.mp3.reduce((n,x)=>n+x.bytes,0)<3_000_000);pass('Guided start loads only bounded current/upcoming English clips',{unique,bytes:report.mp3.reduce((n,x)=>n+x.bytes,0)});await q.getByRole('button',{name:'Pause',exact:true}).click();await q.getByRole('button',{name:'Resume',exact:true}).waitFor();await q.getByRole('button',{name:'Resume',exact:true}).click();await q.getByRole('button',{name:'Pause',exact:true}).waitFor();pass('Actual guided narration pause/resume remains functional');await q.getByRole('button',{name:'End early',exact:true}).click();await q.getByRole('button',{name:'End session',exact:true}).click();await q.locator('#focus-timer-hub').waitFor();
  // Reload online destroys the decoded-memory adapter while keeping verified CacheStorage bytes.
  await q.reload();await q.locator('#focus-timer-hub').waitFor();await q.getByRole('button',{name:'Guided',exact:true}).click();const before=report.mp3.length;await audio.context.setOffline(true);await q.locator('[data-guided-session]').first().getByRole('button',{name:/^Preview voice:/}).click();await q.locator('[data-guidance-mode="recorded"]').waitFor();await Promise.all(pending);assert.equal(report.mp3.length,before);pass('Approved English clip replays offline from verified persistent cache after adapter reload');await screenshot(q,'offline-recorded-english-preview-390');await audio.context.setOffline(false);
 }finally{await audio.context.close()}
 await Promise.all(pending);assert.deepEqual(report.pageErrors,[]);pass('No browser page errors');report.hashesAfter=verify();report.finishedAtUtc=new Date().toISOString();
}catch(e){report.error={name:e.name,message:e.message,stack:e.stack};throw e}finally{await browser.close();fs.writeFileSync(out+'/report.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({sourceCommit:report.sourceCommit,checks:report.checks.length,pngs:report.screenshots.length,external:report.externalBlocked,error:report.error}))}
