/** Generated by scripts/build-course-catalog.ts. Keep full lesson text off the first-use path. */
const EDITIONS = {
  "en": [
    {
      "id": "turning-day",
      "lang": "en",
      "title": "Turning Point Day",
      "subtitle": "One day, the first evidence.",
      "description": "Turn a single day into a real beginning in five short sessions: choose a direction, plan for the obstacle, take the first small step, and turn it into evidence over the next 7 days. Confidence grows from small proof like this.",
      "outcome": "An area you chose and your reason for it, an if–then plan, a first small step taken today, a prepared environment, one supporter, a written evidence note and a 7-day follow-up plan.",
      "minutes": 47,
      "lessonCount": 6,
      "lessonIds": [
        "turning-day-1",
        "turning-day-2",
        "turning-day-3",
        "turning-day-4",
        "turning-day-5",
        "turning-day-6"
      ],
      "lessons": [
        {
          "id": "turning-day-1",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 0
        },
        {
          "id": "turning-day-2",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "turning-day-3",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "turning-day-4",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "turning-day-5",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "turning-day-6",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        }
      ]
    },
    {
      "id": "procrastination",
      "lang": "en",
      "title": "Procrastination",
      "subtitle": "Not laziness, a feeling.",
      "description": "Notice the feeling behind putting things off, shrink the task, attach a plan to your real obstacle, and come back after procrastinating without beating yourself up.",
      "outcome": "A shrunken task, an if–then plan and a sentence for coming back after you have procrastinated.",
      "minutes": 36,
      "lessonCount": 5,
      "lessonIds": [
        "procrastination-1",
        "procrastination-2",
        "procrastination-3",
        "procrastination-4",
        "procrastination-5"
      ],
      "lessons": [
        {
          "id": "procrastination-1",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "procrastination-2",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 2
        },
        {
          "id": "procrastination-3",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 0
        },
        {
          "id": "procrastination-4",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 2
        },
        {
          "id": "procrastination-5",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        }
      ]
    },
    {
      "id": "confidence",
      "lang": "en",
      "title": "Confidence",
      "subtitle": "One step, even when you are scared.",
      "description": "Notice your inner critic, choose a safe experiment, and move forward on the strength of your own effort.",
      "outcome": "A courage step that fits you and a plan for trying again.",
      "minutes": 35,
      "lessonCount": 5,
      "lessonIds": [
        "confidence-1",
        "confidence-2",
        "confidence-3",
        "confidence-4",
        "confidence-5"
      ],
      "lessons": [
        {
          "id": "confidence-1",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "confidence-2",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 2
        },
        {
          "id": "confidence-3",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "confidence-4",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 0
        },
        {
          "id": "confidence-5",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        }
      ]
    },
    {
      "id": "adhd",
      "lang": "en",
      "title": "Everyday life with ADHD",
      "subtitle": "Structure that fits your mind.",
      "description": "Try small tools for getting started, making time visible and finding your way back when your attention drifts.",
      "outcome": "One task list, a tested work interval and a plan for getting back on track.",
      "minutes": 36,
      "lessonCount": 5,
      "lessonIds": [
        "adhd-1",
        "adhd-2",
        "adhd-3",
        "adhd-4",
        "adhd-5"
      ],
      "lessons": [
        {
          "id": "adhd-1",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 2
        },
        {
          "id": "adhd-2",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "adhd-3",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 0
        },
        {
          "id": "adhd-4",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "adhd-5",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 2
        }
      ]
    },
    {
      "id": "motivation",
      "lang": "en",
      "title": "Motivation",
      "subtitle": "Make starting easier.",
      "description": "Link what you want to a small behavior, prepare for obstacles and find your way back when your rhythm breaks.",
      "outcome": "A starting cue, an obstacle plan and a weekly check-in.",
      "minutes": 34,
      "lessonCount": 5,
      "lessonIds": [
        "motivation-1",
        "motivation-2",
        "motivation-3",
        "motivation-4",
        "motivation-5"
      ],
      "lessons": [
        {
          "id": "motivation-1",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "motivation-2",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 2
        },
        {
          "id": "motivation-3",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 2
        },
        {
          "id": "motivation-4",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "motivation-5",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 0
        }
      ]
    },
    {
      "id": "faith",
      "lang": "en",
      "title": "Faith",
      "subtitle": "Trust, gratitude and effort.",
      "description": "Listen to your intention, make your gratitude concrete and add to your hope a kindness you can do today.",
      "outcome": "An intention of your own, a thank-you you can give and a small kindness plan.",
      "minutes": 34,
      "lessonCount": 5,
      "lessonIds": [
        "faith-1",
        "faith-2",
        "faith-3",
        "faith-4",
        "faith-5"
      ],
      "lessons": [
        {
          "id": "faith-1",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "faith-2",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 2
        },
        {
          "id": "faith-3",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "faith-4",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 0
        },
        {
          "id": "faith-5",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 2
        }
      ]
    },
    {
      "id": "manifest",
      "lang": "en",
      "title": "Manifest",
      "subtitle": "From intention to action.",
      "description": "Get clear on what you want, rehearse the path in your mind, face the real obstacle and plan your first step.",
      "outcome": "One goal, a short mental rehearsal, a response to your main obstacle and a date to review how it went.",
      "minutes": 36,
      "lessonCount": 5,
      "lessonIds": [
        "manifest-1",
        "manifest-2",
        "manifest-3",
        "manifest-4",
        "manifest-5"
      ],
      "lessons": [
        {
          "id": "manifest-1",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "manifest-2",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 0
        },
        {
          "id": "manifest-3",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 2
        },
        {
          "id": "manifest-4",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "manifest-5",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        }
      ]
    },
    {
      "id": "focus",
      "lang": "en",
      "title": "Focus",
      "subtitle": "Your attention is limited; take good care of it.",
      "description": "See what switching between tasks costs you, tidy up your notifications, check the claims about phones against the evidence, try short breaks and build your own focus plan.",
      "outcome": "Tidied-up notifications, a focus block you have actually tried and a plan for breaks.",
      "minutes": 36,
      "lessonCount": 5,
      "lessonIds": [
        "focus-1",
        "focus-2",
        "focus-3",
        "focus-4",
        "focus-5"
      ],
      "lessons": [
        {
          "id": "focus-1",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 2
        },
        {
          "id": "focus-2",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 0
        },
        {
          "id": "focus-3",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "focus-4",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 2
        },
        {
          "id": "focus-5",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        }
      ]
    },
    {
      "id": "sleep",
      "lang": "en",
      "title": "Sleep and energy",
      "subtitle": "Give your rest a rhythm.",
      "description": "Get to know how much sleep you need, time your light and caffeine, know what to do when you can’t sleep, and learn when to ask for help.",
      "outcome": "A fixed wake-up time, an evening cut-off for caffeine and screens, a plan for nights when you can’t sleep, and a list of signs that mean it is time to get help.",
      "minutes": 36,
      "lessonCount": 5,
      "lessonIds": [
        "sleep-1",
        "sleep-2",
        "sleep-3",
        "sleep-4",
        "sleep-5"
      ],
      "lessons": [
        {
          "id": "sleep-1",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "sleep-2",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 2
        },
        {
          "id": "sleep-3",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 0
        },
        {
          "id": "sleep-4",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 2
        },
        {
          "id": "sleep-5",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        }
      ]
    },
    {
      "id": "calm",
      "lang": "en",
      "title": "Stress and calm",
      "subtitle": "Make room around the tension.",
      "description": "Notice and name stress, lengthen your exhale, get your body moving, look at the situation from another angle, and know when to ask for help.",
      "outcome": "Your own stress signals, a breathing exercise you have tried, a short movement plan, a perspective question and a list of people and services to turn to.",
      "minutes": 36,
      "lessonCount": 5,
      "lessonIds": [
        "calm-1",
        "calm-2",
        "calm-3",
        "calm-4",
        "calm-5"
      ],
      "lessons": [
        {
          "id": "calm-1",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "calm-2",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 2
        },
        {
          "id": "calm-3",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 0
        },
        {
          "id": "calm-4",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "calm-5",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 2
        }
      ]
    },
    {
      "id": "meditation",
      "lang": "en",
      "title": "How to meditate",
      "subtitle": "Attention that starts with the breath.",
      "description": "Try breath awareness, the body scan, a repeated word, walking, loving-kindness and Dr. Joe Dispenza’s mental rehearsal, one step at a time. Along the way, learn honestly what research does and does not support for each technique.",
      "outcome": "Six techniques you have actually tried, a daily 10-minute routine that suits you, a backup plan for hard days, and a clear list of when to stop and ask for help.",
      "minutes": 55,
      "lessonCount": 7,
      "lessonIds": [
        "meditation-1",
        "meditation-2",
        "meditation-3",
        "meditation-4",
        "meditation-5",
        "meditation-6",
        "meditation-7"
      ],
      "lessons": [
        {
          "id": "meditation-1",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "meditation-2",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "meditation-3",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 2
        },
        {
          "id": "meditation-4",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "meditation-5",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 2
        },
        {
          "id": "meditation-6",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "meditation-7",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 0
        }
      ]
    },
    {
      "id": "suggestion",
      "lang": "en",
      "title": "Self-suggestion",
      "subtitle": "Talk to yourself kindly.",
      "description": "Try well-known suggestion techniques step by step, from Coué and Murphy to Kross and Dispenza, and learn what research says about each of them.",
      "outcome": "A suggestion sentence you can believe, an image, an if–then plan and a personal suggestion card you will review after 7 days.",
      "minutes": 62,
      "lessonCount": 7,
      "lessonIds": [
        "suggestion-1",
        "suggestion-2",
        "suggestion-3",
        "suggestion-4",
        "suggestion-5",
        "suggestion-6",
        "suggestion-7"
      ],
      "lessons": [
        {
          "id": "suggestion-1",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "suggestion-2",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "suggestion-3",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "suggestion-4",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 0
        },
        {
          "id": "suggestion-5",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 0
        },
        {
          "id": "suggestion-6",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 0
        },
        {
          "id": "suggestion-7",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        }
      ]
    },
    {
      "id": "identity",
      "lang": "en",
      "title": "New Self",
      "subtitle": "Change who you are, one small vote at a time.",
      "description": "What if lasting change starts with who you think you are, not only with what you force yourself to do? Learn to spot your old self on autopilot and practice a new one, in a short morning rehearsal and in small proof every day.",
      "outcome": "A written portrait of your old self and the new self you are choosing, a 10-minute morning rehearsal, three if-then plans for your hardest moments, and a weekly review to carry you through the first months.",
      "minutes": 65,
      "lessonCount": 7,
      "lessonIds": [
        "identity-1",
        "identity-2",
        "identity-3",
        "identity-4",
        "identity-5",
        "identity-6",
        "identity-7"
      ],
      "lessons": [
        {
          "id": "identity-1",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "identity-2",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 2
        },
        {
          "id": "identity-3",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 0
        },
        {
          "id": "identity-4",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "identity-5",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 0
        },
        {
          "id": "identity-6",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 2
        },
        {
          "id": "identity-7",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        }
      ]
    },
    {
      "id": "state",
      "lang": "en",
      "title": "Change Your State",
      "subtitle": "Shift how you feel on purpose, in minutes.",
      "description": "Learn short, practical ways to move from tense or flat to steady and ready, using your body, your focus and your words. Each tool from coach Tony Robbins is checked against the research, including the parts that did not hold up.",
      "outcome": "A personal toolkit of seven state-changers you have tried: a triad check, a two-minute body reset, cyclic sighing, a set of better questions, a label-and-reframe routine, a ten-minute morning priming with one honest incantation, and one new standard with a daily action, plus a clear picture of what each tool can and cannot do.",
      "minutes": 61,
      "lessonCount": 7,
      "lessonIds": [
        "state-1",
        "state-2",
        "state-3",
        "state-4",
        "state-5",
        "state-6",
        "state-7"
      ],
      "lessons": [
        {
          "id": "state-1",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 2
        },
        {
          "id": "state-2",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "state-3",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 0
        },
        {
          "id": "state-4",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 2
        },
        {
          "id": "state-5",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "state-6",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "state-7",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 0
        }
      ]
    },
    {
      "id": "optimism",
      "lang": "en",
      "title": "Learned Optimism",
      "subtitle": "Change the story you tell yourself after a setback.",
      "description": "Setbacks hurt, and the story you tell yourself about them decides how long they keep hurting. Learn to catch that story, test it, and replace it with one that is kinder and more accurate.",
      "outcome": "A clear picture of your explanatory style, a pocket ABCDE routine, a thought record you know how to fill in, four questions for stressful thoughts, a worst–best–most-likely check and a nightly three good things habit, plus an honest sense of what each tool can and cannot do.",
      "minutes": 57,
      "lessonCount": 6,
      "lessonIds": [
        "optimism-1",
        "optimism-2",
        "optimism-3",
        "optimism-4",
        "optimism-5",
        "optimism-6"
      ],
      "lessons": [
        {
          "id": "optimism-1",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "optimism-2",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 2
        },
        {
          "id": "optimism-3",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 0
        },
        {
          "id": "optimism-4",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "optimism-5",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 2
        },
        {
          "id": "optimism-6",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 0
        }
      ]
    },
    {
      "id": "meaning",
      "lang": "en",
      "title": "Meaning and Values",
      "subtitle": "Find what matters to you, then take one small step toward it today",
      "description": "What if meaning is less a big answer you find once and more a direction you choose again each day? This course brings together Viktor Frankl’s ideas about meaning and the values work of Acceptance and Commitment Therapy, and turns them into small, daily decisions.",
      "outcome": "A map of where meaning already shows up in your life, a short list of values in your own words, a check for which of them are truly yours, a way to face hard situations you cannot change, a written picture of your best possible future, and one small values-based decision you can make every day.",
      "minutes": 54,
      "lessonCount": 6,
      "lessonIds": [
        "meaning-1",
        "meaning-2",
        "meaning-3",
        "meaning-4",
        "meaning-5",
        "meaning-6"
      ],
      "lessons": [
        {
          "id": "meaning-1",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "meaning-2",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 2
        },
        {
          "id": "meaning-3",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 0
        },
        {
          "id": "meaning-4",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 2
        },
        {
          "id": "meaning-5",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "meaning-6",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        }
      ]
    },
    {
      "id": "stoic",
      "lang": "en",
      "title": "Stoic Calm",
      "subtitle": "Ancient tools for putting your energy where it can do some good",
      "description": "What would change if you spent your energy only on what is actually yours to move? This course turns five Stoic practices into short daily exercises and checks each one honestly against modern psychology.",
      "outcome": "A control sort for any worry, a way to catch the judgment between an event and your reaction, a gentle version of rehearsing setbacks, a step-back technique for heated moments, a five-minute evening review, and one small decision you act on today.",
      "minutes": 51,
      "lessonCount": 6,
      "lessonIds": [
        "stoic-1",
        "stoic-2",
        "stoic-3",
        "stoic-4",
        "stoic-5",
        "stoic-6"
      ],
      "lessons": [
        {
          "id": "stoic-1",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "stoic-2",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 2
        },
        {
          "id": "stoic-3",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "stoic-4",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 0
        },
        {
          "id": "stoic-5",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "stoic-6",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 2
        }
      ]
    },
    {
      "id": "compassion",
      "lang": "en",
      "title": "Self-Compassion",
      "subtitle": "Treat yourself like someone you love, and still own your mistakes",
      "description": "What if the voice in your head could be honest and on your side at the same time? This course explores what research and practice say about self-compassion, and how it can make taking responsibility easier, not harder.",
      "outcome": "A clear picture of what self-compassion is and is not, a two-minute self-compassion break for hard moments, a way to read your threat, drive and soothing systems, a plan for the next time shame hits, and a compassionate letter that ends in one concrete, accountable step.",
      "minutes": 57,
      "lessonCount": 6,
      "lessonIds": [
        "compassion-1",
        "compassion-2",
        "compassion-3",
        "compassion-4",
        "compassion-5",
        "compassion-6"
      ],
      "lessons": [
        {
          "id": "compassion-1",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 0
        },
        {
          "id": "compassion-2",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 0
        },
        {
          "id": "compassion-3",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 0
        },
        {
          "id": "compassion-4",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 0
        },
        {
          "id": "compassion-5",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 0
        },
        {
          "id": "compassion-6",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 0
        }
      ]
    }
  ],
  "tr": [
    {
      "id": "turning-day",
      "lang": "tr",
      "title": "Dönüm Noktası Günü",
      "subtitle": "Bir gün, ilk kanıt.",
      "description": "Tek bir günü beş kısa oturumla gerçek bir başlangıca çevir: yön seç, engeli planla, ilk küçük adımı at ve sonraki 7 günde bunu kanıta dönüştür. Özgüven, bu küçük kanıtlarla büyür.",
      "outcome": "Seçtiğin bir alan ve nedeni, bir eğer/o zaman planı, bugün atılmış ilk küçük adım, hazırlanmış bir ortam, bir destekçi, yazılı bir kanıt notu ve 7 günlük takip planı.",
      "minutes": 47,
      "lessonCount": 6,
      "lessonIds": [
        "turning-day-1",
        "turning-day-2",
        "turning-day-3",
        "turning-day-4",
        "turning-day-5",
        "turning-day-6"
      ],
      "lessons": [
        {
          "id": "turning-day-1",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 0
        },
        {
          "id": "turning-day-2",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "turning-day-3",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "turning-day-4",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "turning-day-5",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "turning-day-6",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        }
      ]
    },
    {
      "id": "procrastination",
      "lang": "tr",
      "title": "Erteleme",
      "subtitle": "Tembellik değil, bir his.",
      "description": "Ertelemenin ardındaki hissi fark et, işi küçült, gerçek engeline bir plan bağla ve erteledikten sonra kendine yüklenmeden geri dön.",
      "outcome": "Küçültülmüş bir görev, eğer/o zaman planı ve erteledikten sonra geri dönüş cümlesi.",
      "minutes": 36,
      "lessonCount": 5,
      "lessonIds": [
        "procrastination-1",
        "procrastination-2",
        "procrastination-3",
        "procrastination-4",
        "procrastination-5"
      ],
      "lessons": [
        {
          "id": "procrastination-1",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "procrastination-2",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 2
        },
        {
          "id": "procrastination-3",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 0
        },
        {
          "id": "procrastination-4",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 2
        },
        {
          "id": "procrastination-5",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        }
      ]
    },
    {
      "id": "confidence",
      "lang": "tr",
      "title": "Özgüven",
      "subtitle": "Korksan da bir adım.",
      "description": "İçindeki eleştirmeni fark et, güvenli bir deneme seç ve kendi emeğine dayanarak ilerle.",
      "outcome": "Sana uygun bir cesaret adımı ve yeniden deneme planı.",
      "minutes": 35,
      "lessonCount": 5,
      "lessonIds": [
        "confidence-1",
        "confidence-2",
        "confidence-3",
        "confidence-4",
        "confidence-5"
      ],
      "lessons": [
        {
          "id": "confidence-1",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "confidence-2",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 2
        },
        {
          "id": "confidence-3",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "confidence-4",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 0
        },
        {
          "id": "confidence-5",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        }
      ]
    },
    {
      "id": "adhd",
      "lang": "tr",
      "title": "ADHD ile günlük yaşam",
      "subtitle": "Zihnine uygun bir düzen.",
      "description": "Başlamayı, zamanı görünür kılmayı ve dikkat dağıldığında geri dönmeyi küçük araçlarla dene.",
      "outcome": "Bir görev listesi, denenmiş bir çalışma aralığı ve geri dönüş planı.",
      "minutes": 36,
      "lessonCount": 5,
      "lessonIds": [
        "adhd-1",
        "adhd-2",
        "adhd-3",
        "adhd-4",
        "adhd-5"
      ],
      "lessons": [
        {
          "id": "adhd-1",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 2
        },
        {
          "id": "adhd-2",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "adhd-3",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 0
        },
        {
          "id": "adhd-4",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "adhd-5",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 2
        }
      ]
    },
    {
      "id": "motivation",
      "lang": "tr",
      "title": "Motivasyon",
      "subtitle": "Başlamayı kolaylaştır.",
      "description": "İsteğini küçük bir davranışa bağla, engellere hazırlan ve ritmin bozulduğunda geri dön.",
      "outcome": "Bir başlangıç işareti, engel planı ve haftalık değerlendirme.",
      "minutes": 34,
      "lessonCount": 5,
      "lessonIds": [
        "motivation-1",
        "motivation-2",
        "motivation-3",
        "motivation-4",
        "motivation-5"
      ],
      "lessons": [
        {
          "id": "motivation-1",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "motivation-2",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 2
        },
        {
          "id": "motivation-3",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 2
        },
        {
          "id": "motivation-4",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "motivation-5",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 0
        }
      ]
    },
    {
      "id": "faith",
      "lang": "tr",
      "title": "İnanç",
      "subtitle": "Tevekkül, şükür ve emek.",
      "description": "Niyetini dinle, şükrünü somutlaştır ve umuduna bugün yapılabilecek bir iyilik ekle.",
      "outcome": "Kendine ait bir niyet, teşekkür ifadesi ve küçük iyilik planı.",
      "minutes": 34,
      "lessonCount": 5,
      "lessonIds": [
        "faith-1",
        "faith-2",
        "faith-3",
        "faith-4",
        "faith-5"
      ],
      "lessons": [
        {
          "id": "faith-1",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "faith-2",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 2
        },
        {
          "id": "faith-3",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "faith-4",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 0
        },
        {
          "id": "faith-5",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 2
        }
      ]
    },
    {
      "id": "manifest",
      "lang": "tr",
      "title": "Manifest",
      "subtitle": "Niyetten eyleme.",
      "description": "Ne istediğini netleştir, süreci zihninde prova et, gerçek engeli gör ve ilk adımını planla.",
      "outcome": "Bir hedef, zihinsel prova, engel yanıtı ve gözden geçirme tarihi.",
      "minutes": 36,
      "lessonCount": 5,
      "lessonIds": [
        "manifest-1",
        "manifest-2",
        "manifest-3",
        "manifest-4",
        "manifest-5"
      ],
      "lessons": [
        {
          "id": "manifest-1",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "manifest-2",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 0
        },
        {
          "id": "manifest-3",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 2
        },
        {
          "id": "manifest-4",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "manifest-5",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        }
      ]
    },
    {
      "id": "focus",
      "lang": "tr",
      "title": "Odak",
      "subtitle": "Dikkatin sınırlı; ona iyi bak.",
      "description": "Görev değiştirmenin bedelini gör, bildirimlerini düzenle, telefon hakkındaki iddiaları kanıtla karşılaştır, kısa molaları dene ve kendi odak planını kur.",
      "outcome": "Düzenlenmiş bildirimler, denenmiş bir odak bloğu ve mola planı.",
      "minutes": 36,
      "lessonCount": 5,
      "lessonIds": [
        "focus-1",
        "focus-2",
        "focus-3",
        "focus-4",
        "focus-5"
      ],
      "lessons": [
        {
          "id": "focus-1",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 2
        },
        {
          "id": "focus-2",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 0
        },
        {
          "id": "focus-3",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "focus-4",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 2
        },
        {
          "id": "focus-5",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        }
      ]
    },
    {
      "id": "sleep",
      "lang": "tr",
      "title": "Uyku ve enerji",
      "subtitle": "Dinlenmeye bir ritim ver.",
      "description": "Uyku ihtiyacını tanı, ışığı ve kafeini zamanla, uyuyamadığında ne yapacağını bil ve ne zaman yardım isteyeceğini öğren.",
      "outcome": "Sabit bir kalkış saati, akşam için kafein ve ekran sınırı, uyuyamadığında uygulayacağın bir plan ve yardım işaretleri listesi.",
      "minutes": 36,
      "lessonCount": 5,
      "lessonIds": [
        "sleep-1",
        "sleep-2",
        "sleep-3",
        "sleep-4",
        "sleep-5"
      ],
      "lessons": [
        {
          "id": "sleep-1",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "sleep-2",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 2
        },
        {
          "id": "sleep-3",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 0
        },
        {
          "id": "sleep-4",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 2
        },
        {
          "id": "sleep-5",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        }
      ]
    },
    {
      "id": "calm",
      "lang": "tr",
      "title": "Stres ve sakinlik",
      "subtitle": "Gerginliğe alan aç.",
      "description": "Stresi fark edip adlandır, nefes verişini uzat, bedenini hareket ettir, duruma başka bir açıdan bak ve ne zaman yardım isteyeceğini bil.",
      "outcome": "Kendi stres işaretlerin, denenmiş bir nefes alıştırması, kısa bir hareket planı, bir bakış açısı sorusu ve destek listesi.",
      "minutes": 36,
      "lessonCount": 5,
      "lessonIds": [
        "calm-1",
        "calm-2",
        "calm-3",
        "calm-4",
        "calm-5"
      ],
      "lessons": [
        {
          "id": "calm-1",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "calm-2",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 2
        },
        {
          "id": "calm-3",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 0
        },
        {
          "id": "calm-4",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "calm-5",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 2
        }
      ]
    },
    {
      "id": "meditation",
      "lang": "tr",
      "title": "Meditasyon nasıl yapılır",
      "subtitle": "Nefesle başlayan dikkat.",
      "description": "Nefes, beden taraması, kelime tekrarı, yürüyüş, sevgi-şefkat ve Dr. Joe Dispenza’nın zihinsel provasını adım adım dene. Her tekniğin araştırmada neyle desteklendiğini de dürüstçe öğren.",
      "outcome": "Denenmiş altı meditasyon tekniği, sana uyan günlük 10 dakikalık bir düzen, zor günler için yedek bir plan ve ne zaman durup yardım isteyeceğini gösteren bir liste.",
      "minutes": 54,
      "lessonCount": 7,
      "lessonIds": [
        "meditation-1",
        "meditation-2",
        "meditation-3",
        "meditation-4",
        "meditation-5",
        "meditation-6",
        "meditation-7"
      ],
      "lessons": [
        {
          "id": "meditation-1",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "meditation-2",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "meditation-3",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 2
        },
        {
          "id": "meditation-4",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "meditation-5",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 2
        },
        {
          "id": "meditation-6",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "meditation-7",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 0
        }
      ]
    },
    {
      "id": "suggestion",
      "lang": "tr",
      "title": "Telkin nasıl verilir",
      "subtitle": "Kendinle nazik konuş.",
      "description": "Coué’den Murphy’ye, Kross’tan Dispenza’ya ünlü telkin tekniklerini adım adım uygula ve araştırmaların bu teknikler hakkında ne dediğini öğren.",
      "outcome": "İnanabileceğin bir telkin cümlesi, bir imge, bir eğer–o zaman planı ve 7 gün sonra gözden geçireceğin kişisel telkin kartın.",
      "minutes": 55,
      "lessonCount": 7,
      "lessonIds": [
        "suggestion-1",
        "suggestion-2",
        "suggestion-3",
        "suggestion-4",
        "suggestion-5",
        "suggestion-6",
        "suggestion-7"
      ],
      "lessons": [
        {
          "id": "suggestion-1",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "suggestion-2",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "suggestion-3",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "suggestion-4",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 0
        },
        {
          "id": "suggestion-5",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 0
        },
        {
          "id": "suggestion-6",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 0
        },
        {
          "id": "suggestion-7",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        }
      ]
    },
    {
      "id": "identity",
      "lang": "tr",
      "title": "Yeni Benlik",
      "subtitle": "Kim olduğunu değiştir, her seferinde küçük bir oyla.",
      "description": "Ya kalıcı değişim yalnızca kendini neye zorladığınla değil, kim olduğunu sandığınla başlıyorsa? Otopilottaki eski benliğini fark etmeyi ve yenisini uygulamayı öğren: kısa bir sabah provasıyla ve her gün küçük kanıtlarla.",
      "outcome": "Eski benliğinin ve seçtiğin yeni benliğin yazılı bir portresi, 10 dakikalık bir sabah provası, en zor anların için üç eğer-öyleyse planı ve ilk aylarda sana eşlik edecek haftalık bir gözden geçirme.",
      "minutes": 65,
      "lessonCount": 7,
      "lessonIds": [
        "identity-1",
        "identity-2",
        "identity-3",
        "identity-4",
        "identity-5",
        "identity-6",
        "identity-7"
      ],
      "lessons": [
        {
          "id": "identity-1",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "identity-2",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 2
        },
        {
          "id": "identity-3",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 0
        },
        {
          "id": "identity-4",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "identity-5",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 0
        },
        {
          "id": "identity-6",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 2
        },
        {
          "id": "identity-7",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        }
      ]
    },
    {
      "id": "state",
      "lang": "tr",
      "title": "Halini Değiştir",
      "subtitle": "Nasıl hissettiğini bilerek, dakikalar içinde değiştir.",
      "description": "Bedenini, odağını ve sözcüklerini kullanarak gergin ya da dümdüz bir halden dengeli ve hazır bir hale geçmenin kısa, pratik yollarını öğren. Koç Tony Robbins’in her aracı, tutmayan kısımlar da dahil, araştırmalarla karşılaştırılıyor.",
      "outcome": "Denemiş olduğun yedi hal değiştiriciden oluşan kişisel bir araç seti: üçlü kontrolü, iki dakikalık bir beden sıfırlaması, döngüsel iç çekme, daha iyi sorular, adlandır ve yeniden çerçevele rutini, tek bir dürüst telkinle on dakikalık bir sabah hazırlanması, günlük bir eylemle yeni bir standart; ayrıca her aracın neyi yapıp neyi yapamayacağının net bir resmi.",
      "minutes": 61,
      "lessonCount": 7,
      "lessonIds": [
        "state-1",
        "state-2",
        "state-3",
        "state-4",
        "state-5",
        "state-6",
        "state-7"
      ],
      "lessons": [
        {
          "id": "state-1",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 2
        },
        {
          "id": "state-2",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "state-3",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 0
        },
        {
          "id": "state-4",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 2
        },
        {
          "id": "state-5",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "state-6",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "state-7",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 0
        }
      ]
    },
    {
      "id": "optimism",
      "lang": "tr",
      "title": "Öğrenilmiş İyimserlik",
      "subtitle": "Bir aksilikten sonra kendine anlattığın hikâyeyi değiştir.",
      "description": "Aksilikler acıtır; ne kadar süre acıtacağını ise kendine anlattığın hikâye belirler. Bu hikâyeyi yakalamayı, sınamayı ve yerine daha nazik ve daha doğru birini koymayı öğren.",
      "outcome": "Kendi açıklama biçimine dair net bir resim, cebinde taşıyabileceğin bir ABCDE rutini, nasıl dolduracağını bildiğin bir düşünce kaydı, stres veren düşünceler için dört soru, en kötü–en iyi–en olası kontrolü ve her akşam sürdürebileceğin bir üç iyi şey alışkanlığı; ayrıca her aracın neyi yapıp neyi yapamayacağına dair dürüst bir fikir.",
      "minutes": 57,
      "lessonCount": 6,
      "lessonIds": [
        "optimism-1",
        "optimism-2",
        "optimism-3",
        "optimism-4",
        "optimism-5",
        "optimism-6"
      ],
      "lessons": [
        {
          "id": "optimism-1",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "optimism-2",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 2
        },
        {
          "id": "optimism-3",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 0
        },
        {
          "id": "optimism-4",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "optimism-5",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 2
        },
        {
          "id": "optimism-6",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 0
        }
      ]
    },
    {
      "id": "meaning",
      "lang": "tr",
      "title": "Anlam ve Değerler",
      "subtitle": "Senin için neyin önemli olduğunu bul, sonra bugün ona doğru küçük bir adım at",
      "description": "Peki ya anlam, bir kez bulunan büyük bir cevaptan çok, her gün yeniden seçtiğin bir yönse? Bu kurs, Viktor Frankl’ın anlam üzerine fikirlerini ve Kabul ve Kararlılık Terapisi’nin değerler çalışmasını bir araya getirip küçük, günlük kararlara dönüştürüyor.",
      "outcome": "Anlamın hayatında zaten nerelerde göründüğünü gösteren bir harita, kendi sözcüklerinle yazılmış kısa bir değer listesi, hangilerinin gerçekten sana ait olduğunu anlamak için bir kontrol, değiştiremeyeceğin zor durumlarla yüzleşmenin bir yolu, en iyi olası geleceğinin yazılı bir resmi ve her gün verebileceğin küçük bir değer temelli karar.",
      "minutes": 54,
      "lessonCount": 6,
      "lessonIds": [
        "meaning-1",
        "meaning-2",
        "meaning-3",
        "meaning-4",
        "meaning-5",
        "meaning-6"
      ],
      "lessons": [
        {
          "id": "meaning-1",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "meaning-2",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 2
        },
        {
          "id": "meaning-3",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 0
        },
        {
          "id": "meaning-4",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 2
        },
        {
          "id": "meaning-5",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "meaning-6",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        }
      ]
    },
    {
      "id": "stoic",
      "lang": "tr",
      "title": "Stoacı Dinginlik",
      "subtitle": "Enerjini işe yarayabileceği yere koymak için kadim araçlar",
      "description": "Enerjini yalnızca gerçekten senin elinde olan şeylere harcasan neler değişirdi? Bu kurs beş Stoacı uygulamayı kısa günlük alıştırmalara dönüştürüyor ve her birini modern psikolojiyle dürüstçe karşılaştırıyor.",
      "outcome": "Her kaygı için bir kontrol ayrıştırması, olayla tepkin arasındaki yargıyı yakalama yolu, aksilikleri zihinde prova etmenin nazik bir hâli, gergin anlar için bir geri çekilme tekniği, beş dakikalık bir akşam değerlendirmesi ve bugün harekete geçeceğin küçük bir karar.",
      "minutes": 51,
      "lessonCount": 6,
      "lessonIds": [
        "stoic-1",
        "stoic-2",
        "stoic-3",
        "stoic-4",
        "stoic-5",
        "stoic-6"
      ],
      "lessons": [
        {
          "id": "stoic-1",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "stoic-2",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 2
        },
        {
          "id": "stoic-3",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "stoic-4",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 0
        },
        {
          "id": "stoic-5",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "stoic-6",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 2
        }
      ]
    },
    {
      "id": "compassion",
      "lang": "tr",
      "title": "Öz Şefkat",
      "subtitle": "Kendine sevdiğin biri gibi davran ve yine de hatalarının sorumluluğunu al",
      "description": "Kafandaki ses aynı anda hem dürüst hem senin yanında olabilseydi? Bu kurs, öz şefkat hakkında araştırma ve uygulamanın ne söylediğini ve bunun sorumluluk almayı nasıl zorlaştırmak yerine kolaylaştırabileceğini keşfediyor.",
      "outcome": "Öz şefkatin ne olduğu ve ne olmadığına dair net bir resim, zor anlar için iki dakikalık bir öz şefkat molası, tehdit, dürtü ve yatışma sistemlerini okuma yolu, utanç bir dahaki sefere vurduğunda uygulayacağın bir plan ve somut, hesap verebilir tek bir adımla biten şefkatli bir mektup.",
      "minutes": 57,
      "lessonCount": 6,
      "lessonIds": [
        "compassion-1",
        "compassion-2",
        "compassion-3",
        "compassion-4",
        "compassion-5",
        "compassion-6"
      ],
      "lessons": [
        {
          "id": "compassion-1",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 0
        },
        {
          "id": "compassion-2",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 0
        },
        {
          "id": "compassion-3",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 0
        },
        {
          "id": "compassion-4",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 0
        },
        {
          "id": "compassion-5",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 0
        },
        {
          "id": "compassion-6",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 0
        }
      ]
    }
  ],
  "es": [
    {
      "id": "turning-day",
      "lang": "es",
      "title": "El día del punto de inflexión",
      "subtitle": "Un día, la primera evidencia.",
      "description": "Convierte un solo día en un verdadero comienzo en cinco sesiones cortas: elige una dirección, prepárate para el obstáculo, da el primer paso pequeño y transfórmalo en evidencia durante los próximos 7 días. La confianza crece con pruebas pequeñas como esta.",
      "outcome": "Un área que elegiste y tu razón para ello, un plan «si… entonces…», un primer paso pequeño dado hoy, un entorno preparado, una persona de apoyo, una nota de evidencia escrita y un plan de seguimiento de 7 días.",
      "minutes": 47,
      "lessonCount": 6,
      "lessonIds": [
        "turning-day-1",
        "turning-day-2",
        "turning-day-3",
        "turning-day-4",
        "turning-day-5",
        "turning-day-6"
      ],
      "lessons": [
        {
          "id": "turning-day-1",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 0
        },
        {
          "id": "turning-day-2",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "turning-day-3",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "turning-day-4",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "turning-day-5",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "turning-day-6",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        }
      ]
    },
    {
      "id": "procrastination",
      "lang": "es",
      "title": "Procrastinación",
      "subtitle": "No es pereza, es un sentimiento.",
      "description": "Nota el sentimiento que hay detrás de dejar las cosas para después, reduce la tarea, ata un plan a tu obstáculo real y vuelve después de procrastinar sin castigarte.",
      "outcome": "Una tarea reducida, un plan «si… entonces…» y una frase para volver después de haber procrastinado.",
      "minutes": 36,
      "lessonCount": 5,
      "lessonIds": [
        "procrastination-1",
        "procrastination-2",
        "procrastination-3",
        "procrastination-4",
        "procrastination-5"
      ],
      "lessons": [
        {
          "id": "procrastination-1",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "procrastination-2",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 2
        },
        {
          "id": "procrastination-3",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 0
        },
        {
          "id": "procrastination-4",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 2
        },
        {
          "id": "procrastination-5",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        }
      ]
    },
    {
      "id": "confidence",
      "lang": "es",
      "title": "Confianza",
      "subtitle": "Un paso, aunque tengas miedo.",
      "description": "Nota a tu crítico interior, elige un experimento seguro y avanza apoyándote en tu propio esfuerzo.",
      "outcome": "Un paso de valentía que te quede bien y un plan para volver a intentarlo.",
      "minutes": 35,
      "lessonCount": 5,
      "lessonIds": [
        "confidence-1",
        "confidence-2",
        "confidence-3",
        "confidence-4",
        "confidence-5"
      ],
      "lessons": [
        {
          "id": "confidence-1",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "confidence-2",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 2
        },
        {
          "id": "confidence-3",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "confidence-4",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 0
        },
        {
          "id": "confidence-5",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        }
      ]
    },
    {
      "id": "adhd",
      "lang": "es",
      "title": "La vida diaria con TDAH",
      "subtitle": "Una estructura que se adapta a tu mente.",
      "description": "Prueba pequeñas herramientas para empezar, hacer visible el tiempo y encontrar el camino de vuelta cuando tu atención se dispersa.",
      "outcome": "Una lista de tareas, un intervalo de trabajo probado y un plan para retomar el rumbo.",
      "minutes": 36,
      "lessonCount": 5,
      "lessonIds": [
        "adhd-1",
        "adhd-2",
        "adhd-3",
        "adhd-4",
        "adhd-5"
      ],
      "lessons": [
        {
          "id": "adhd-1",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 2
        },
        {
          "id": "adhd-2",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "adhd-3",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 0
        },
        {
          "id": "adhd-4",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "adhd-5",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 2
        }
      ]
    },
    {
      "id": "motivation",
      "lang": "es",
      "title": "Motivación",
      "subtitle": "Haz que empezar sea más fácil.",
      "description": "Vincula lo que quieres con una conducta pequeña, prepárate para los obstáculos y encuentra el camino de vuelta cuando se rompa tu ritmo.",
      "outcome": "Una señal de inicio, un plan para los obstáculos y una revisión semanal.",
      "minutes": 34,
      "lessonCount": 5,
      "lessonIds": [
        "motivation-1",
        "motivation-2",
        "motivation-3",
        "motivation-4",
        "motivation-5"
      ],
      "lessons": [
        {
          "id": "motivation-1",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "motivation-2",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 2
        },
        {
          "id": "motivation-3",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 2
        },
        {
          "id": "motivation-4",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "motivation-5",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 0
        }
      ]
    },
    {
      "id": "faith",
      "lang": "es",
      "title": "Fe",
      "subtitle": "Confianza, gratitud y esfuerzo.",
      "description": "Escucha tu intención, haz concreta tu gratitud y suma a tu esperanza una amabilidad que puedas hacer hoy.",
      "outcome": "Una intención propia, un agradecimiento que puedas dar y un pequeño plan de amabilidad.",
      "minutes": 34,
      "lessonCount": 5,
      "lessonIds": [
        "faith-1",
        "faith-2",
        "faith-3",
        "faith-4",
        "faith-5"
      ],
      "lessons": [
        {
          "id": "faith-1",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "faith-2",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 2
        },
        {
          "id": "faith-3",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "faith-4",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 0
        },
        {
          "id": "faith-5",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 2
        }
      ]
    },
    {
      "id": "manifest",
      "lang": "es",
      "title": "Manifestar",
      "subtitle": "De la intención a la acción.",
      "description": "Aclara lo que quieres, ensaya el camino en tu mente, enfrenta el obstáculo real y planifica tu primer paso.",
      "outcome": "Una meta, un breve ensayo mental, una respuesta a tu principal obstáculo y una fecha para revisar cómo te fue.",
      "minutes": 36,
      "lessonCount": 5,
      "lessonIds": [
        "manifest-1",
        "manifest-2",
        "manifest-3",
        "manifest-4",
        "manifest-5"
      ],
      "lessons": [
        {
          "id": "manifest-1",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "manifest-2",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 0
        },
        {
          "id": "manifest-3",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 2
        },
        {
          "id": "manifest-4",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "manifest-5",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        }
      ]
    },
    {
      "id": "focus",
      "lang": "es",
      "title": "Enfoque",
      "subtitle": "Tu atención es limitada; cuídala bien.",
      "description": "Descubre lo que te cuesta cambiar de una tarea a otra, ordena tus notificaciones, contrasta con la evidencia lo que se dice de los teléfonos, prueba descansos cortos y construye tu propio plan de enfoque.",
      "outcome": "Notificaciones ordenadas, un bloque de enfoque que hayas probado de verdad y un plan para tus descansos.",
      "minutes": 36,
      "lessonCount": 5,
      "lessonIds": [
        "focus-1",
        "focus-2",
        "focus-3",
        "focus-4",
        "focus-5"
      ],
      "lessons": [
        {
          "id": "focus-1",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 2
        },
        {
          "id": "focus-2",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 0
        },
        {
          "id": "focus-3",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "focus-4",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 2
        },
        {
          "id": "focus-5",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        }
      ]
    },
    {
      "id": "sleep",
      "lang": "es",
      "title": "Sueño y energía",
      "subtitle": "Dale un ritmo a tu descanso.",
      "description": "Conoce cuánto sueño necesitas, ajusta tus horarios de luz y cafeína, aprende qué hacer cuando no puedes dormir y descubre cuándo pedir ayuda.",
      "outcome": "Una hora fija para despertarte, un límite por la tarde-noche para la cafeína y las pantallas, un plan para las noches en que no puedes dormir y una lista de señales que indican que es momento de buscar ayuda.",
      "minutes": 36,
      "lessonCount": 5,
      "lessonIds": [
        "sleep-1",
        "sleep-2",
        "sleep-3",
        "sleep-4",
        "sleep-5"
      ],
      "lessons": [
        {
          "id": "sleep-1",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "sleep-2",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 2
        },
        {
          "id": "sleep-3",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 0
        },
        {
          "id": "sleep-4",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 2
        },
        {
          "id": "sleep-5",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        }
      ]
    },
    {
      "id": "calm",
      "lang": "es",
      "title": "Estrés y calma",
      "subtitle": "Haz espacio alrededor de la tensión.",
      "description": "Reconoce y nombra el estrés, alarga tu exhalación, pon el cuerpo en movimiento, mira la situación desde otro ángulo y aprende a saber cuándo pedir ayuda.",
      "outcome": "Tus propias señales de estrés, un ejercicio de respiración que ya probaste, un breve plan de movimiento, una pregunta para cambiar de perspectiva y una lista de personas y servicios a los que acudir.",
      "minutes": 36,
      "lessonCount": 5,
      "lessonIds": [
        "calm-1",
        "calm-2",
        "calm-3",
        "calm-4",
        "calm-5"
      ],
      "lessons": [
        {
          "id": "calm-1",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "calm-2",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 2
        },
        {
          "id": "calm-3",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 0
        },
        {
          "id": "calm-4",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "calm-5",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 2
        }
      ]
    },
    {
      "id": "meditation",
      "lang": "es",
      "title": "Cómo meditar",
      "subtitle": "Una atención que empieza con la respiración.",
      "description": "Prueba, paso a paso, la conciencia de la respiración, el escaneo corporal, una palabra repetida, la caminata, la bondad amorosa y el ensayo mental del Dr. Joe Dispenza. Por el camino, descubre con honestidad qué respalda y qué no respalda la investigación en cada técnica.",
      "outcome": "Seis técnicas que has probado de verdad, una rutina diaria de 10 minutos que se ajusta a ti, un plan de respaldo para los días difíciles y una lista clara de cuándo detenerte y pedir ayuda.",
      "minutes": 55,
      "lessonCount": 7,
      "lessonIds": [
        "meditation-1",
        "meditation-2",
        "meditation-3",
        "meditation-4",
        "meditation-5",
        "meditation-6",
        "meditation-7"
      ],
      "lessons": [
        {
          "id": "meditation-1",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "meditation-2",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "meditation-3",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 2
        },
        {
          "id": "meditation-4",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "meditation-5",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 2
        },
        {
          "id": "meditation-6",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "meditation-7",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 0
        }
      ]
    },
    {
      "id": "suggestion",
      "lang": "es",
      "title": "Autosugestión",
      "subtitle": "Háblate con amabilidad.",
      "description": "Prueba paso a paso técnicas de sugestión muy conocidas, de Coué y Murphy a Kross y Dispenza, y descubre qué dice la investigación sobre cada una de ellas.",
      "outcome": "Una frase de sugestión en la que puedas creer, una imagen, un plan «si… entonces…» y una tarjeta personal de sugestión que revisarás después de 7 días.",
      "minutes": 62,
      "lessonCount": 7,
      "lessonIds": [
        "suggestion-1",
        "suggestion-2",
        "suggestion-3",
        "suggestion-4",
        "suggestion-5",
        "suggestion-6",
        "suggestion-7"
      ],
      "lessons": [
        {
          "id": "suggestion-1",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "suggestion-2",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "suggestion-3",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "suggestion-4",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 0
        },
        {
          "id": "suggestion-5",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 0
        },
        {
          "id": "suggestion-6",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 0
        },
        {
          "id": "suggestion-7",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        }
      ]
    },
    {
      "id": "identity",
      "lang": "es",
      "title": "Nuevo yo",
      "subtitle": "Cambia quién eres, un pequeño voto a la vez.",
      "description": "¿Y si el cambio duradero empieza por quién crees que eres, y no solo por lo que te obligas a hacer? Aprende a reconocer a tu viejo yo en piloto automático y a practicar uno nuevo, con un breve ensayo matutino y con pequeñas pruebas cada día.",
      "outcome": "Un retrato escrito de tu viejo yo y del nuevo yo que eliges, un ensayo matutino de 10 minutos, tres planes si-entonces para tus momentos más difíciles y una revisión semanal que te acompañe durante los primeros meses.",
      "minutes": 65,
      "lessonCount": 7,
      "lessonIds": [
        "identity-1",
        "identity-2",
        "identity-3",
        "identity-4",
        "identity-5",
        "identity-6",
        "identity-7"
      ],
      "lessons": [
        {
          "id": "identity-1",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "identity-2",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 2
        },
        {
          "id": "identity-3",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 0
        },
        {
          "id": "identity-4",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "identity-5",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 0
        },
        {
          "id": "identity-6",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 2
        },
        {
          "id": "identity-7",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        }
      ]
    },
    {
      "id": "state",
      "lang": "es",
      "title": "Cambia tu estado",
      "subtitle": "Cambia cómo te sientes a propósito, en minutos.",
      "description": "Aprende formas breves y prácticas de pasar de la tensión o el desánimo a estar firme y listo, usando tu cuerpo, tu foco y tus palabras. Cada herramienta del coach Tony Robbins se contrasta con la investigación, incluidas las partes que no resistieron.",
      "outcome": "Un kit personal de siete cambiadores de estado que ya probaste: una revisión de la tríada, un reinicio corporal de dos minutos, el suspiro cíclico, un conjunto de mejores preguntas, una rutina de nombrar y reencuadrar, un priming matutino de diez minutos con una invocación honesta y un nuevo estándar con una acción diaria, además de una idea clara de lo que cada herramienta puede y no puede hacer.",
      "minutes": 61,
      "lessonCount": 7,
      "lessonIds": [
        "state-1",
        "state-2",
        "state-3",
        "state-4",
        "state-5",
        "state-6",
        "state-7"
      ],
      "lessons": [
        {
          "id": "state-1",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 2
        },
        {
          "id": "state-2",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "state-3",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 0
        },
        {
          "id": "state-4",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 2
        },
        {
          "id": "state-5",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "state-6",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "state-7",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 0
        }
      ]
    },
    {
      "id": "optimism",
      "lang": "es",
      "title": "Optimismo aprendido",
      "subtitle": "Cambia la historia que te cuentas después de un contratiempo.",
      "description": "Los contratiempos duelen, y la historia que te cuentas sobre ellos decide cuánto tiempo siguen doliendo. Aprende a atrapar esa historia, ponerla a prueba y sustituirla por otra más amable y más exacta.",
      "outcome": "Una idea clara de tu estilo explicativo, una rutina ABCDE de bolsillo, un registro de pensamientos que sabes cómo completar, cuatro preguntas para los pensamientos estresantes, una revisión de peor–mejor–más probable y un hábito nocturno de tres cosas buenas, además de una idea honesta de lo que cada herramienta puede y no puede hacer.",
      "minutes": 57,
      "lessonCount": 6,
      "lessonIds": [
        "optimism-1",
        "optimism-2",
        "optimism-3",
        "optimism-4",
        "optimism-5",
        "optimism-6"
      ],
      "lessons": [
        {
          "id": "optimism-1",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "optimism-2",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 2
        },
        {
          "id": "optimism-3",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 0
        },
        {
          "id": "optimism-4",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "optimism-5",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 2
        },
        {
          "id": "optimism-6",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 0
        }
      ]
    },
    {
      "id": "meaning",
      "lang": "es",
      "title": "Sentido y valores",
      "subtitle": "Descubre lo que te importa y da hoy un pequeño paso hacia ello",
      "description": "¿Y si el sentido no fuera tanto una gran respuesta que se encuentra una sola vez, sino una dirección que eliges de nuevo cada día? Este curso reúne las ideas de Viktor Frankl sobre el sentido y el trabajo con valores de la Terapia de Aceptación y Compromiso, y las convierte en pequeñas decisiones diarias.",
      "outcome": "Un mapa de dónde ya aparece el sentido en tu vida, una lista corta de valores en tus propias palabras, una forma de comprobar cuáles son de verdad tuyos, una manera de afrontar las situaciones difíciles que no puedes cambiar, una imagen escrita de tu mejor futuro posible y una pequeña decisión basada en tus valores que puedes tomar cada día.",
      "minutes": 54,
      "lessonCount": 6,
      "lessonIds": [
        "meaning-1",
        "meaning-2",
        "meaning-3",
        "meaning-4",
        "meaning-5",
        "meaning-6"
      ],
      "lessons": [
        {
          "id": "meaning-1",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "meaning-2",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 2
        },
        {
          "id": "meaning-3",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 0
        },
        {
          "id": "meaning-4",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 2
        },
        {
          "id": "meaning-5",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "meaning-6",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        }
      ]
    },
    {
      "id": "stoic",
      "lang": "es",
      "title": "Calma estoica",
      "subtitle": "Herramientas antiguas para poner tu energía donde puede hacer algo de bien",
      "description": "¿Qué cambiaría si gastaras tu energía solo en lo que de verdad te toca mover? Este curso convierte cinco prácticas estoicas en ejercicios diarios breves y contrasta cada una, con honestidad, con la psicología moderna.",
      "outcome": "Una clasificación del control para cualquier preocupación, una forma de detectar el juicio que hay entre un hecho y tu reacción, una versión suave de ensayar los contratiempos, una técnica de dar un paso atrás en los momentos acalorados, un repaso nocturno de cinco minutos y una pequeña decisión que pones en práctica hoy.",
      "minutes": 51,
      "lessonCount": 6,
      "lessonIds": [
        "stoic-1",
        "stoic-2",
        "stoic-3",
        "stoic-4",
        "stoic-5",
        "stoic-6"
      ],
      "lessons": [
        {
          "id": "stoic-1",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "stoic-2",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 2
        },
        {
          "id": "stoic-3",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "stoic-4",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 0
        },
        {
          "id": "stoic-5",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 1
        },
        {
          "id": "stoic-6",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 2
        }
      ]
    },
    {
      "id": "compassion",
      "lang": "es",
      "title": "Autocompasión",
      "subtitle": "Trátate como a alguien a quien quieres, y aun así asume tus errores",
      "description": "¿Y si la voz en tu cabeza pudiera ser honesta y estar de tu lado al mismo tiempo? Este curso explora lo que dicen la investigación y la práctica sobre la autocompasión, y cómo puede hacer que asumir la responsabilidad sea más fácil, no más difícil.",
      "outcome": "Una idea clara de lo que es y lo que no es la autocompasión, una pausa de autocompasión de dos minutos para los momentos difíciles, una forma de leer tus sistemas de amenaza, impulso y calma, un plan para la próxima vez que te golpee la vergüenza y una carta compasiva que termina en un paso concreto y responsable.",
      "minutes": 57,
      "lessonCount": 6,
      "lessonIds": [
        "compassion-1",
        "compassion-2",
        "compassion-3",
        "compassion-4",
        "compassion-5",
        "compassion-6"
      ],
      "lessons": [
        {
          "id": "compassion-1",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 0
        },
        {
          "id": "compassion-2",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 0
        },
        {
          "id": "compassion-3",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 0
        },
        {
          "id": "compassion-4",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 0
        },
        {
          "id": "compassion-5",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 0
        },
        {
          "id": "compassion-6",
          "practiceCount": 3,
          "optionCount": 3,
          "correct": 0
        }
      ]
    }
  ]
};

export type CourseCatalogEntry = (typeof EDITIONS.en)[number];
export function courseCatalogFor(locale: string): CourseCatalogEntry[] {
  return locale === 'tr' ? EDITIONS.tr : locale === 'es' ? EDITIONS.es : EDITIONS.en;
}
