/** Generated by scripts/generate-responsive-images.py; approved originals are retained. */
export const IMAGE_DELIVERY_ASSETS = {
  "assets/oda/course-covers/oda-starting-procrastination.png": [
    {
      "src": "assets/oda/delivery/course-covers/oda-starting-procrastination-320.webp",
      "width": 320,
      "height": 180
    },
    {
      "src": "assets/oda/delivery/course-covers/oda-starting-procrastination-400.webp",
      "width": 400,
      "height": 225
    },
    {
      "src": "assets/oda/delivery/course-covers/oda-starting-procrastination-640.webp",
      "width": 640,
      "height": 360
    },
    {
      "src": "assets/oda/delivery/course-covers/oda-starting-procrastination-800.webp",
      "width": 800,
      "height": 450
    },
    {
      "src": "assets/oda/delivery/course-covers/oda-starting-procrastination-960.webp",
      "width": 960,
      "height": 540
    },
    {
      "src": "assets/oda/delivery/course-covers/oda-starting-procrastination-1280.webp",
      "width": 1280,
      "height": 720
    },
    {
      "src": "assets/oda/delivery/course-covers/oda-starting-procrastination-1672.webp",
      "width": 1672,
      "height": 941
    }
  ],
  "assets/oda/course-covers/oda-focus.png": [
    {
      "src": "assets/oda/delivery/course-covers/oda-focus-320.webp",
      "width": 320,
      "height": 180
    },
    {
      "src": "assets/oda/delivery/course-covers/oda-focus-400.webp",
      "width": 400,
      "height": 225
    },
    {
      "src": "assets/oda/delivery/course-covers/oda-focus-640.webp",
      "width": 640,
      "height": 360
    },
    {
      "src": "assets/oda/delivery/course-covers/oda-focus-800.webp",
      "width": 800,
      "height": 450
    },
    {
      "src": "assets/oda/delivery/course-covers/oda-focus-960.webp",
      "width": 960,
      "height": 540
    },
    {
      "src": "assets/oda/delivery/course-covers/oda-focus-1280.webp",
      "width": 1280,
      "height": 720
    },
    {
      "src": "assets/oda/delivery/course-covers/oda-focus-1672.webp",
      "width": 1672,
      "height": 940
    }
  ],
  "assets/oda/course-covers/oda-reflection-emotion.png": [
    {
      "src": "assets/oda/delivery/course-covers/oda-reflection-emotion-320.webp",
      "width": 320,
      "height": 180
    },
    {
      "src": "assets/oda/delivery/course-covers/oda-reflection-emotion-400.webp",
      "width": 400,
      "height": 225
    },
    {
      "src": "assets/oda/delivery/course-covers/oda-reflection-emotion-640.webp",
      "width": 640,
      "height": 360
    },
    {
      "src": "assets/oda/delivery/course-covers/oda-reflection-emotion-800.webp",
      "width": 800,
      "height": 450
    },
    {
      "src": "assets/oda/delivery/course-covers/oda-reflection-emotion-960.webp",
      "width": 960,
      "height": 540
    },
    {
      "src": "assets/oda/delivery/course-covers/oda-reflection-emotion-1280.webp",
      "width": 1280,
      "height": 720
    },
    {
      "src": "assets/oda/delivery/course-covers/oda-reflection-emotion-1672.webp",
      "width": 1672,
      "height": 941
    }
  ],
  "assets/oda/course-covers/oda-growth-values.png": [
    {
      "src": "assets/oda/delivery/course-covers/oda-growth-values-320.webp",
      "width": 320,
      "height": 180
    },
    {
      "src": "assets/oda/delivery/course-covers/oda-growth-values-400.webp",
      "width": 400,
      "height": 225
    },
    {
      "src": "assets/oda/delivery/course-covers/oda-growth-values-640.webp",
      "width": 640,
      "height": 360
    },
    {
      "src": "assets/oda/delivery/course-covers/oda-growth-values-800.webp",
      "width": 800,
      "height": 450
    },
    {
      "src": "assets/oda/delivery/course-covers/oda-growth-values-960.webp",
      "width": 960,
      "height": 540
    },
    {
      "src": "assets/oda/delivery/course-covers/oda-growth-values-1280.webp",
      "width": 1280,
      "height": 720
    },
    {
      "src": "assets/oda/delivery/course-covers/oda-growth-values-1672.webp",
      "width": 1672,
      "height": 941
    }
  ],
  "assets/oda/trees/tree-00-seedling-0.png": [
    {
      "src": "assets/oda/delivery/trees/tree-00-seedling-0-320.webp",
      "width": 320,
      "height": 320
    },
    {
      "src": "assets/oda/delivery/trees/tree-00-seedling-0-480.webp",
      "width": 480,
      "height": 480
    },
    {
      "src": "assets/oda/delivery/trees/tree-00-seedling-0-640.webp",
      "width": 640,
      "height": 640
    },
    {
      "src": "assets/oda/delivery/trees/tree-00-seedling-0-960.webp",
      "width": 960,
      "height": 960
    },
    {
      "src": "assets/oda/delivery/trees/tree-00-seedling-0-1254.webp",
      "width": 1254,
      "height": 1254
    }
  ],
  "assets/oda/trees/tree-01-sapling-1-9.png": [
    {
      "src": "assets/oda/delivery/trees/tree-01-sapling-1-9-320.webp",
      "width": 320,
      "height": 320
    },
    {
      "src": "assets/oda/delivery/trees/tree-01-sapling-1-9-480.webp",
      "width": 480,
      "height": 480
    },
    {
      "src": "assets/oda/delivery/trees/tree-01-sapling-1-9-640.webp",
      "width": 640,
      "height": 640
    },
    {
      "src": "assets/oda/delivery/trees/tree-01-sapling-1-9-960.webp",
      "width": 960,
      "height": 960
    },
    {
      "src": "assets/oda/delivery/trees/tree-01-sapling-1-9-1254.webp",
      "width": 1254,
      "height": 1254
    }
  ],
  "assets/oda/trees/tree-02-young-10-29.png": [
    {
      "src": "assets/oda/delivery/trees/tree-02-young-10-29-320.webp",
      "width": 320,
      "height": 320
    },
    {
      "src": "assets/oda/delivery/trees/tree-02-young-10-29-480.webp",
      "width": 480,
      "height": 480
    },
    {
      "src": "assets/oda/delivery/trees/tree-02-young-10-29-640.webp",
      "width": 640,
      "height": 640
    },
    {
      "src": "assets/oda/delivery/trees/tree-02-young-10-29-960.webp",
      "width": 960,
      "height": 960
    },
    {
      "src": "assets/oda/delivery/trees/tree-02-young-10-29-1254.webp",
      "width": 1254,
      "height": 1254
    }
  ],
  "assets/oda/trees/tree-03-fuller-30-59.png": [
    {
      "src": "assets/oda/delivery/trees/tree-03-fuller-30-59-320.webp",
      "width": 320,
      "height": 320
    },
    {
      "src": "assets/oda/delivery/trees/tree-03-fuller-30-59-480.webp",
      "width": 480,
      "height": 480
    },
    {
      "src": "assets/oda/delivery/trees/tree-03-fuller-30-59-640.webp",
      "width": 640,
      "height": 640
    },
    {
      "src": "assets/oda/delivery/trees/tree-03-fuller-30-59-960.webp",
      "width": 960,
      "height": 960
    },
    {
      "src": "assets/oda/delivery/trees/tree-03-fuller-30-59-1254.webp",
      "width": 1254,
      "height": 1254
    }
  ],
  "assets/oda/trees/tree-04-mature-60-plus.png": [
    {
      "src": "assets/oda/delivery/trees/tree-04-mature-60-plus-320.webp",
      "width": 320,
      "height": 320
    },
    {
      "src": "assets/oda/delivery/trees/tree-04-mature-60-plus-480.webp",
      "width": 480,
      "height": 480
    },
    {
      "src": "assets/oda/delivery/trees/tree-04-mature-60-plus-640.webp",
      "width": 640,
      "height": 640
    },
    {
      "src": "assets/oda/delivery/trees/tree-04-mature-60-plus-960.webp",
      "width": 960,
      "height": 960
    },
    {
      "src": "assets/oda/delivery/trees/tree-04-mature-60-plus-1254.webp",
      "width": 1254,
      "height": 1254
    }
  ],
  "assets/oda/trees/tree-05-flowering-61-90.png": [
    {
      "src": "assets/oda/delivery/trees/tree-05-flowering-61-90-320.webp",
      "width": 320,
      "height": 320
    },
    {
      "src": "assets/oda/delivery/trees/tree-05-flowering-61-90-480.webp",
      "width": 480,
      "height": 480
    },
    {
      "src": "assets/oda/delivery/trees/tree-05-flowering-61-90-640.webp",
      "width": 640,
      "height": 640
    },
    {
      "src": "assets/oda/delivery/trees/tree-05-flowering-61-90-960.webp",
      "width": 960,
      "height": 960
    },
    {
      "src": "assets/oda/delivery/trees/tree-05-flowering-61-90-1254.webp",
      "width": 1254,
      "height": 1254
    }
  ]
} as const;
